### ISSUE TITLE
The ¨No Windows Bounds¨ still cause issues with Glasscord.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Lightcord/Lightcord#10]
Already reported here : https://discord.com/channels/705908350218666117/712995915878760449/730765648489218059

The thing being, that on some Linux Desktop Environnement. (Tested on AwesomeWM, and Xubuntu, so this isn´t caused by my tilling windows manager), the Glasstron implementation breaks. This is caused by Lightcord saving the last Lightcord window process position, size and status (Maximised or not) in the lightcord settings.json

```json
   1   │ {
   2   │   "BACKGROUND_COLOR": "#ffffff",
   3   │   "IS_MAXIMIZED": false,
   4   │   "IS_MINIMIZED": false,
   5   │   "WINDOW_BOUNDS": {
   6   │     "x": 1787,
   7   │     "y": 39,
   8   │     "width": 1645,
   9   │     "height": 1393
  10   │   },
  11   │   "LAST_UPDATE_CHECK_TIMESTAMP": 1596276667823,
  12   │   "NO_WINDOWS_BOUND": true
  13   │ }
```

To fix that issue, the ¨NO\_WINDOWS\_BOUND¨ parameter was added, but still cause that issue, even if it is ticked on.

I would suggest when ¨NO\_WINDOWS\_BOUND¨ is set to true in the settings.json file, that it erase or comment out the `"WINDOW_BOUNDS", "IS_MINIMIZED" & "IS_MAXIMIZED"` parameters, and revert it when ticked off.

```json
   1   │ {
   2   │   "LAST_UPDATE_CHECK_TIMESTAMP": 1596123547403,
   3   │   "BACKGROUND_COLOR": "#ffffff",
   4   │ }
```

**Comment by PoorPocketsMcNewHold** [comment]
It's still happening to me, and to another user, encountered on the Lightcord server, using picom/compton this time.
https://discord.com/channels/705908350218666117/712993189484691497/766726305042923560

**Comment by pryme-svg** [comment]
Using picom, I was able to fix it by just deleting the settings.json file altogether and restarting lightcord

**Comment by pryme-svg** [comment]
It also tries to edit the file every time the app is restarted  so I just add an rm command to the desktop file

**Comment by PoorPocketsMcNewHold** [comment]
I habitually just restrict the write usage.

**Comment by MegaShinySnivy** [comment]
I hate to bump an old issues like this, but this is still happening on KDE plasma. Is there no fix other than RMing the settings.json file?
