### ISSUE TITLE
Plugins and Themes Settings not showing up correctly

### ISSUE THREAD

**Issue by Bluthekirb** [Lightcord/Lightcord#100]
Everytime I go to the settings for both plugins and themes, it keeps showing up incorrectly with a wumpus error?
![unknown](https://user-images.githubusercontent.com/43391273/98386743-8e185880-201e-11eb-93d2-bcdb27306244.png)
![unknown](https://user-images.githubusercontent.com/43391273/98386940-d0da3080-201e-11eb-98f3-f6d4fe8a190f.png)

**Comment by JeanOUINA** [comment]
duplicate of #54
