### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by ControlAlternateDelete** [Lightcord/Lightcord#105]
**Describe the bug**
All in the title

**To Reproduce**
1. Make sure overlay is enabled for your game
2. Run the game

**Expected behavior**
Overlay should work by pressing Shift + '

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 20H2

**Comment by JeanOUINA** [comment]
Lightcord may have problems with things like:
 - Overlay (Discord uses a [modified version of electron](https://github.com/discord/electron), we can't build it right now)
 - Krisp (They check the executable signing, which make Krisp unusable on a non-Discord Patch.)
 - Spellcheck
 - No Auto Updates
 - Login/Register captcha may not work. Log in using your phone/token if you're stuck.
