### ISSUE TITLE
[BUG]Multiple plug-ins incorrectly labelled as "dangerous"

### ISSUE THREAD

**Issue by asorel1942** [Lightcord/Lightcord#108]
Several BetterDiscord plugins (specifically libraries used by other plug-ins) are being marked as dangerous by Lightcord and will not load in the app. These include XenoLib (required for SaveToRedux and others), and BDFDB (required for BetterFriendList).

**To Reproduce**

1. Open Lightcord with problem plugins installed
2. Wait for plugins to be loaded.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/33983895/99031284-ba633600-2544-11eb-9516-959b2369217c.png)
![image](https://user-images.githubusercontent.com/33983895/99031314-cb13ac00-2544-11eb-9892-00d6753e9280.png)
![image](https://user-images.githubusercontent.com/33983895/99031351-da92f500-2544-11eb-9097-c7a27a40c32b.png)
![image](https://user-images.githubusercontent.com/33983895/99031373-e8e11100-2544-11eb-8448-5835ea123108.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/33983895/99031395-f8605a00-2544-11eb-8e92-d63e6e1a4e6b.png)

**Additional context**

**Comment by JeanOUINA** [comment]
For XenoLib, read the reason.
0BDFDB should be good now.

**Comment by asorel1942** [comment]
0BDFDB appears to be having this issue again.
