### ISSUE TITLE
[BUG] Emoji picker and other elements with wrong colors with actual dark theme

### ISSUE THREAD

**Issue by busybox11** [Lightcord/Lightcord#109]
**Describe the bug**
Some elements, such as the emoji picker or the message toolbar, are not styled with the actual dark theme color (see screenshot).

**To Reproduce**
- Access to any element which has this bug
    * e.g. Emoji picker
    * Message toolbar
    * T.A.Y.N.E.

**Expected behavior**
The colors should be the same everywhere.

**Screenshots**
![image](https://user-images.githubusercontent.com/29630035/99517410-a0d04d00-298f-11eb-8d1c-cd6d495e9cd3.png)
![image](https://user-images.githubusercontent.com/29630035/99518529-fc4f0a80-2990-11eb-932a-a734a806fe2e.png)

**Desktop (please complete the following information):**
```
Stable 71715 (060524d)
Lightcord 0.1.4 (55208fd)
BBD 0.3.5 (lightcord)
Host 0.0.308
Linux 64-Bit (5.9.1-Arch1-1)
```

**Comment by JeanOUINA** [comment]
This comes from the theme you're using, Not lightcord.

(btw you can search on github if the theme has an update. Go in *settings > Themes* and check the enabled theme, then search it on github).

**Comment by busybox11** [comment]
I know this comes from the theme I'm using.

Thing is, the theme I'm using is bundled with Lightcord, that's why I reported this here.
