### ISSUE TITLE
[BUG] BDFDB Incorrectly Labeled as "Threat" or "Dangerous"

### ISSUE THREAD

**Issue by syns** [Lightcord/Lightcord#110]
**Bug Description:**
A BetterDiscord Library for multiple Plugins known as BDFDB is being detected as a "threat" or "dangerous" plugin by Lightcord and will not load in the application without the workaround of disabling "Scan Plugins" under BetterDiscord Settings.

**Reproduction:**
I. Open Lightcord with "Threat" Plugins needing updating (or installed)
II. Allow Lightcord to Load Plugins
III. Be Prompted Regarding Content Error of Plugins

**Expected Behaviour:**
The expected behaviour is for the plugins to be loaded without the incorrect positive and disabling of a library necessary for certain plugins.

**Screenshot(s):**
![Error](https://user-images.githubusercontent.com/38664452/100009739-dfea0e00-2d94-11eb-976b-1f63c4d312f0.PNG)

**Desktop Information:**
 - OS: Windows 10 Pro (20H2)
 - Lightcord Version: 0.1.4 (a205515)
 - Bandaged BetterDiscord Version: 0.3.5 (lightcord)

**Additional Context**
This Bug was made an issue previously (#108), however, [it was previously fixed (supposedly), but is now a false positive once again.](https://github.com/Lightcord/Lightcord/issues/108#issuecomment-726551792)
If this isn't a Lightcord issue, it seems the [creator is unwilling to fix the issue on their end if so.](https://github.com/mwittrien/BetterDiscordAddons/issues/536#issuecomment-719776844)

**Comment by JeanOUINA** [comment]
That's not a problem with 0DBFDB itself, but with [lightcord/filehashes](https://github.com/lightcord/filehashes) repo. The repo isn't automatically updated, so plugins that are whitelisted may take some times to update as it's done manually by me.

**Comment by Kyr4l** [comment]
hey, it's still not working

**Comment by vbajs** [comment]
> hey, it's still not working

See this
https://github.com/Lightcord/filehashes/issues/10
