### ISSUE TITLE
Support for ARM devices

### ISSUE THREAD

**Issue by mzoeller** [Lightcord/Lightcord#111]
Hi, has anyone tried using lightcord on ARM devices like the pinephone? It it technically possible?

**Comment by smartfrigde** [comment]
It is possible. I have a partially working build of Lightcord but there are display issues (it's just a black window). I'm 100%  sure someone more experienced in electron stuff can fix this. I'm running it on Pinebook Pro. For Pinephone I recommend you CutTheCord running in Anbox for now, I guess?

**Comment by JeanOUINA** [comment]
@smartfrigde By any chance, are there errors in the console about something called discord_utils_linux.node ?

**Comment by smartfrigde** [comment]
> @smartfrigde By any chance, are there errors in the console about something called discord_utils_linux.node ?
Here's error (it's on left down corner)
![image](https://user-images.githubusercontent.com/37928912/100087399-ef2d9200-2e4e-11eb-816a-f654dc7a15ff.png)

**Comment by JeanOUINA** [comment]
This is just a deprecation warning, but does something happens when you press `ctrl+shift+i` with focus on the window ?

**Comment by smartfrigde** [comment]
![Przechwycenie obrazu ekranu_2020-11-24_15-56-49](https://user-images.githubusercontent.com/37928912/100110824-b3ee8b80-2e6d-11eb-8d2e-1e21dc50be1e.png)
Yup discord_utils_linux.node was the error

**Comment by smartfrigde** [comment]
@JeanOUINA so is there fix for that?

**Comment by JeanOUINA** [comment]
Unlikely. This is one of the binaries Lightcord uses that are from Discord, and they aren't built for ARM. You could try recreating them, but it won't work like that.

**Comment by smartfrigde** [comment]
I will try digging to find problem

**Comment by mzoeller** [comment]
I get two errors when calling nom test:

> Minifying...
> node:internal/fs/utils:814
>   throw new ERR_INVALID_ARG_TYPE(
>   ^
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of SourceMapGenerator
>     at Object.writeFileSync (node:fs:1485:5)
>     at minify (/home/manjaro/Lightcord/BetterDiscordApp/minify-css.js:20:8)
>     at Object.<anonymous> (/home/manjaro/Lightcord/BetterDiscordApp/minify-css.js:35:9)
>     at Module._compile (node:internal/modules/cjs/loader:1102:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
>     at Module.load (node:internal/modules/cjs/loader:967:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:807:14)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
>     at node:internal/main/run_main_module:17:47 {
>   code: 'ERR_INVALID_ARG_TYPE'
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bandagedbd@0.3.5 minify-css: `node minify-css.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the bandagedbd@0.3.5 minify-css script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/manjaro/.npm/_logs/2020-11-24T15_52_38_215Z-debug.log
> 92% chunk asset optimization TerserPluginHash: 4b3d42b5df72f6a99f4a

it continues, though so I think that is not the problem.

later it exits at

> Exiting compilation
> /home/manjaro/Lightcord/node_modules/electron/dist/electron: /home/manjaro/Lightcord/node_modules/electron/dist/electron: cannot execute binary file
> npm ERR! Test failed.  See above for more details.

**Comment by pryme-svg** [comment]
That is because the binary is built for amd64 and cannot be executed on arm, thus `cannot execute binary file`

**Comment by j0lol** [comment]
uh would this help? https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi

**Comment by smartfrigde** [comment]
Not possible without Discord actually making release for Arm. Use Web app or something like [ArmCord](https://github.com/smartfrigde/ArmCord)
