### ISSUE TITLE
click to update prompt for seemingly no reason

### ISSUE THREAD

**Issue by m1492** [Lightcord/Lightcord#113]
**Describe the bug**
A click to update prompt is found at the top of the screen, which is incapable of being removed, and also leaves a blank bar at the top of the screen.

**To Reproduce**
1. install Lightcord on Arch Linux from the AUR
2. login

**Expected behavior**
either a functional update prompt, or no prompt (depending on if there's an update)

**Screenshots**
![2020-11-25_14-16](https://user-images.githubusercontent.com/75043899/100277528-2f7a3680-2f5b-11eb-8d77-83ace5babab9.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version v0.1.4

**Additional context**
-did not install using the installer
-logging in using official discord website does not result in this bug

**Comment by JeanOUINA** [comment]
This is due to ZeresPluginLibrary, try updating it.

**Comment by m1492** [comment]
while the update prompt stayed regardless of whether it needed to be updated or not, removing ZeresPluginLibrary has fixed this issue
