### ISSUE TITLE
[SMALL ISSUE] Logged out when restarting

### ISSUE THREAD

**Issue by Nermal242** [Lightcord/Lightcord#114]
Every time I open the Lightcord file after closing it I am logged out from my account. Is this intended to be or is this a bug?

**Comment by JeanOUINA** [comment]
Are you using the tabs mode ? They reset the localStorage every time, and that's where the token is stored.

**Comment by Nermal242** [comment]
Yes I am using tabs mode

**Comment by JeanOUINA** [comment]
yeah that's the problem. If you want to have your account saved, please disable it.
