### ISSUE TITLE
Why is WebAssembly blacklisted?

### ISSUE THREAD

**Issue by aspenluxxxy** [Lightcord/Lightcord#115]
https://github.com/Lightcord/Lightcord/blob/master/BetterDiscordApp/src/modules/pluginCertifier.js#L48 (let's not mention how dumb this whole "certifier" system is)

There are tons of legitimate uses for WebAssembly, such as:

 - Performance-critical code
 - Security-critical code, such as encryption/hashing
 - Just not wanting to use JS.

**Comment by pryme-svg** [comment]
It is easy to disable.

**Comment by aspenluxxxy** [comment]
@pryme-svg I'm more wondering about the reasoning.

**Comment by pryme-svg** [comment]
https://github.com/Lightcord/Lightcord/commit/76416383d754eb5862f1468998863d3b23d41e21

ask @JeanOUINA

**Comment by ethernalsteve** [comment]
As for me - sooo stupid protection 😂 Controlled by banal wrapping a string in base64
