### ISSUE TITLE
[BUG] Zoom (scale of text and interface) resets when setting it up then clicking on Welcome button

### ISSUE THREAD

**Issue by AkechiShiro** [Lightcord/Lightcord#116]
**Describe the bug**
Zoom (scale of text and interface) resets when setting it up then clicking on Welcome button

**To Reproduce**
1. Go to 'Parameters'
2. Click on 'Appearance'
3. Change "Zoom level" to "150%" using slider.
4. Click on "Welcome button"
5. See error

**Expected behavior**
Zoom level should be kept consistent even if the `Welcome button` is pressed.

**Screenshots**
The button pointed by the red arrow is the one causing the resetting of the zoom/scaled up interface.
[![lightcordbug.png](https://i.postimg.cc/N0DybQFP/lightcordbug.png)](https://postimg.cc/rddFwXSS)

**Desktop (please complete the following information):**
 - OS: `Arch Linux (Linux User 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux)`
 - Version : 
```
(of Lightcord) 0.0.308
releaseChannel: stable
commit: 55208fd4d39f04605353b516dcb097a8ea01ce63
```
**Additional context**
When I use the keyboard hotkeys `'CTRL' + '+'` the zoom scale resets back to the correct set parameter.

**Comment by AkechiShiro** [comment]
I just tested this not only happen with that button, but also with the `Friend` button and the `Nitro` button or on any `MP` chats fields, it looks like it happens with certain types of button and not all clickable things on the interface, I would be glad to try and submit a PR if I had some time to dive into the codebase and understand how this great app works. (It would've helped to have a CONTRIBUTING.md file but that's a feature suggestion that I should open as well to help lower the entry bar for people wanting to help on this project)

**Comment by JeanOUINA** [comment]
I'm pretty sure this is a bug with one of your plugins/discord itself. I can't reproduce, could you please add more informations (for example, your list of plugins) ?

**Comment by AkechiShiro** [comment]
You are correct. This is happening due to this [specific plugin](https://betterdiscordlibrary.com/plugins/ZeresPluginLibrary) (required by some others plugins) which I just deleted and now the bug is gone.

Thank you for the help ! (I should have tested without the plugin on)
