### ISSUE TITLE
This plugin might be dangerous (Account Stealer/Virus).

### ISSUE THREAD

**Issue by ve3xone** [Lightcord/Lightcord#117]
wtf?
![image](https://user-images.githubusercontent.com/39828362/100564013-9c862700-32e1-11eb-93af-d326d2fb2775.png)
ok...... 
![image](https://user-images.githubusercontent.com/39828362/100564029-a4de6200-32e1-11eb-9327-01054f337670.png)

**Comment by Dreomite** [comment]
I've seen this report for [CopyRawMessage](https://github.com/mwittrien/BetterDiscordAddons/blob/master/Plugins/CopyRawMessage/CopyRawMessage.plugin.js) and [ImageUtilities](https://github.com/mwittrien/BetterDiscordAddons/blob/master/Plugins/ImageUtilities/ImageUtilities.plugin.js) plugins. If you're interested, [here's the source](https://github.com/mwittrien/BetterDiscordAddons/blob/master/Library/0BDFDB.plugin.js) of the library.

The maintainer of plugins was notified, but he stated that he writes plugins for BD and not Lightcord, which is fair.

Related: https://github.com/mwittrien/BetterDiscordAddons/issues/575

**Comment by JeanOUINA** [comment]
should be fixed now. Let me know if it isn't.
