### ISSUE TITLE
[ISSUE] Lots of lag when the application is open

### ISSUE THREAD

**Issue by Nermal242** [Lightcord/Lightcord#118]
I have lots of lag when Lightcord is opened. If I close the application the lag is gone. How do I fix these lag issues because Lightcord really lags my system.

**Comment by JeanOUINA** [comment]
try disabling glasstron in Lightcord’s settings

**Comment by Nermal242** [comment]
It worked. Thanks now I have less lag

**Comment by ControlAlternateDelete** [comment]
Will someone close this? the problem has already been solved
