### ISSUE TITLE
[BUG] This plugin might be dangerous.

### ISSUE THREAD

**Issue by shifting-tides** [Lightcord/Lightcord#119]
AccountSwitcher.plugin.js from https://github.com/l0c4lh057/AccountSwitcher.

what made the lightcord say that? Has the code been audited?

**Comment by ControlAlternateDelete** [comment]
BetterDiscord doesn't support account switchers for security reasons.

**Comment by shifting-tides** [comment]
> BetterDiscord doesn't support account switchers for security reasons.
I know, but what makes lightcord say that this plugin is a stealer?
This message is just a common warning then?

**Comment by pryme-svg** [comment]
https://github.com/Lightcord/Lightcord/blob/master/BetterDiscordApp/src/modules/pluginCertifier.js

Read this file if you would like to know

**Comment by JeanOUINA** [comment]
should be fixed now. let me know if it isn't.
