### ISSUE TITLE
[QUESTION]cani be banned for using lightcord

### ISSUE THREAD

**Issue by nonobou31** [Lightcord/Lightcord#12]
the title ask my question

**Comment by JeanOUINA** [comment]
Theorically: yes
Actually: no

While Lightcord **is** again'st Discord's ToS, you have **very low chances** of getting banned.
They're the same as using BetterDiscord/Powercord. Just don't do stupid things like selfbot with Lightcord and you should be fine. You can learn more on BetterDiscord's website https://0x71.cc/bd/guide/#ban
