### ISSUE TITLE
README recommends running easily potentially bad one-liner

### ISSUE THREAD

**Issue by Oj18** [Lightcord/Lightcord#120]
It recommends downloading (via `wget`) a file and instantly running it with `sudo bash` without any mention at all that it could be dangerous or that you should probably check the source before running it as root with bash.

> `wget -N https://raw.githubusercontent.com/Lightcord/Lightcord/master/Lightcord_installer.sh && sudo bash Lightcord_installer.sh`

**Comment by pryme-svg** [comment]
The installer needs root privileges to access `/opt` `/usr/share/applications` and `/usr/share/pixmaps`

**Comment by Oj18** [comment]
That's not the issue I'm talking about; more that it recommends downloading and running it as root without any checking or warning in the readme at all that it can be dangerous (like most projects do when they tell you to download and run any shell scripts).

**Comment by pryme-svg** [comment]
Then edit the readme and open a pr
