### ISSUE TITLE
[BUG] Bandaged_BD and Lightcord functions missing

### ISSUE THREAD

**Issue by asorel1942** [Lightcord/Lightcord#127]
After updating Lightcord, quitting, and re-opening the application, all of my plugins and themes were disabled and Bandaged_BD itself, along with the Lightcord settings, appears to have disappeared from the settings menu.

**To Reproduce**
1. Update Lightcord
2. Restart application

**Expected behavior**
Presence of Bandaged BD and Lightcord settings

**Screenshots**
![image](https://user-images.githubusercontent.com/33983895/101232806-eaa07f00-3681-11eb-8462-b2241fdbfee9.png)

**Desktop (please complete the following information):**
 See bottom of above screenshot

**Additional context**

**Comment by Titaniumtown** [comment]
Same issue! Please fix!

**Comment by JeanOUINA** [comment]
Can you provide error logs ?

1. Press `ctrl`+`shift`+`i` with Lightcord focused
2. Navigate to the console tab in the devtools.
3. (optionally) filter logs to errors only as seen here: <br><br>![e](https://i.lightcord.org/‍‍⁠᠎​‍​⁠‌​.png)
4. Screenshot errors you see, and reply them here.

**Comment by asorel1942** [comment]
![image](https://user-images.githubusercontent.com/33983895/101260008-ca60d680-36fa-11eb-8cf5-12ed0180f0c0.png)
Here's a screenshot of the errors I see.

**Comment by JeanOUINA** [comment]
You're using the lightcord-git aur package by any chance ? try reinstalling.

**Comment by asorel1942** [comment]
Yes, I'm using the lightcord-git package from AUR. Is that the wrong one to be using? It had the most recent last modified date of the three in the repository, so I assumed it was the correct one. Just finished an uninstall and re-build of the package, problem still persists.

**Comment by pryme-svg** [comment]
building from source results in the same problem. However, `npm test` works. `npm build` and running the binary results in same errors. It's not a problem with the package. Maybe the stuff in scripts is broken.

**Comment by pryme-svg** [comment]
fixed by https://github.com/Lightcord/Lightcord/commit/33722854ffe1b7ea3a1b6fea37f82e153eb7d0ca. Just run a `yay -Syu` and you should be good

**Comment by JeanOUINA** [comment]
I'm closing this since it should be fixed. Reopen if you're still facing issues
