### ISSUE TITLE
[FEATURE] Snap or Flatpack

### ISSUE THREAD

**Issue by himynameisulpa** [Lightcord/Lightcord#13]
I would love to try Lightcord, so could you create a snap package so everyone who is using linux can use it? Alternatively flatpack would be nice too.

**Comment by phorcysed** [comment]
we are planning on making an AppImage for lightcord.
there's also an AUR. but snap could be used too, alternatively just run from source / download the binaries, it isn't that hard/annoying lol

**Comment by pryme-svg** [comment]
There is also an install script that was just created today. That automates everything, and it will probably be the main method. Creating packages for every distro deb, rpm, tarxz, etc. isn't very practical. The dev team says that they will be creating an appimage, but you should use the install script for now.

**Comment by pryme-svg** [comment]
can somebody close this issue lmao
