### ISSUE TITLE
[BUG] Current lightcord-git AUR PKGBUILD fails to build

### ISSUE THREAD

**Issue by raku-cat** [Lightcord/Lightcord#130]
**Describe the bug**
The current PKGBUILD posted at lightcord-git in the aur fails to build with errors

**To Reproduce**
1. Clone lightcord-git:
`git clone https://aur.archlinux.org/lightcord-git.git`
2. Change directories to the cloned repo
`cd lightcord-git`
3. Run makepkg:
`makepkg`

**Expected behavior**
The package to build and product an install-able package

**Screenshots**
[![asciicast](https://asciinema.org/a/377890.svg)](https://asciinema.org/a/377890)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version None(?)

**Comment by pryme-svg** [comment]
The package builds successfully for me https://pastebin.com/1g33EyP4

**Comment by raku-cat** [comment]
Commenting the line that throws an error for me in build.js:
`await fs.promises.rmdir("./distApp", {"recursive": true})`
Makes the build work for me, maybe change this to be in a try/catch so it's non-fatal?

```
try {
    await fs.promises.rmdir("./distApp", {"recursive": true})
}
catch (e) {}

**Comment by pryme-svg** [comment]
I could apply a patch downstream. But I’ll see if it get merged into master

**Comment by pryme-svg** [comment]
```
try{
    	await fs.promises.rmdir("./distApp", {"recursive": true})
    } catch (error) {
	    console.error(error);
	}
```

**Comment by pryme-svg** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/?h=lightcord-git&id=53884cdc93b12144ee3b2796ec2f4363a9c1b031

See if that fixes it

**Comment by raku-cat** [comment]
Looks to be working, builds installs and runs :+1:

**Comment by pryme-svg** [comment]
Awesome!
