### ISSUE TITLE
[BUG] Screen Share POP-OUT Window is not working

### ISSUE THREAD

**Issue by chaemoong** [Lightcord/Lightcord#137]
**Describe the bug**

**To Reproduce**

**Expected behavior**
See Screen Sharing and Click Pop Out then unlimit loading but sounds is hearing well

**Screenshots**
![image](https://user-images.githubusercontent.com/49019734/102015370-9b9fcb80-3d9e-11eb-9d00-b0f7c30c8195.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7, Ubuntu, etc...]
 - Version [e.g. v0.1.4]
Stable 73349 (6ee7fbb)
Lightcord 0.1.4 (a205515)
BBD 0.3.5 (lightcord)
Host 0.0.308
Windows 10 64-Bit (10.0.19041)

**Additional context**

**Comment by asorel1942** [comment]
Have the same issue

**Comment by olegrumiancev** [comment]
Have the same issue, did a little digging around in the BetterDiscordApp repo and they had this same problem as well. Linking through to their commit that fixes things https://github.com/rauenzi/BetterDiscordApp/commit/521056b7ef5cb073433dbe1d0caec9d8aaafb4ca 

Hope this is helpful

**Comment by smartfrigde** [comment]
Should be fixed by latest commits
