### ISSUE TITLE
Content error

### ISSUE THREAD

**Issue by rafalohaki** [Lightcord/Lightcord#139]
name:
1XenoLib.plugin.js
Could not be compiled.

error:
XenoLib is not defined

![image](https://user-images.githubusercontent.com/20607107/102589401-41409b00-410f-11eb-9037-3633021519d7.png)

**Comment by JeanOUINA** [comment]
No support will be given for plugins from Lighty.

**Comment by rafalohaki** [comment]
> No support will be given for plugins from Lighty.

it is run by betterdiscord, its working on others but not on this. u mean it is special denied?

**Comment by JeanOUINA** [comment]
I mean that it’s not our fault. The person that did this plugin purposely stopped them from working in Lightcord.
