### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by rappingninjaYT** [Lightcord/Lightcord#140]
Since everyone is ignoring me in the discord.

i got this error everytime i try to install lightcord

https://i.vgy.me/4e5Jr6.png

please help me

i tried running as admin and without running as admin
i moved it from my downloads to my desktop and moved it back to my downloads but same problem i moved it everywhere and tried it but it had same error

**Comment by JeanOUINA** [comment]
It’s likely because of a download problem. Try relaunching the installer, or the zip file was modified by one of your program (like antivirus)

**Comment by rappingninjaYT** [comment]
my antivirus is off
and i downloaded the installer 4 timee

**Comment by ControlAlternateDelete** [comment]
maybe try to download an earlier version of lightcord and let ota updates fix the problem

**Comment by rappingninjaYT** [comment]
it got fixed nvm
