### ISSUE TITLE
[BUG] Crashes when I click on any person from discord server

### ISSUE THREAD

**Issue by Sstiixy** [Lightcord/Lightcord#143]
**Describe the bug**
So when I click on random person or bot in any discord server lightcord crashes

**To Reproduce**
There is no '...' so I can't see the error

**Expected behavior**
It needs not to crash

**Screenshots**
![image](https://user-images.githubusercontent.com/63057428/103138554-1be5fb00-46d4-11eb-920a-650e7a97491f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.19041)
 - Version 0.14 (a205515)

**Additional context**

**Comment by JeanOUINA** [comment]
Disable the `BetterRoleColor` plugin
