### ISSUE TITLE
[BUG] The ringtone remix is shit

### ISSUE THREAD

**Issue by NelOxingale** [Lightcord/Lightcord#147]
The ringtone you remixed from original Discord is terrible, pls fix.

**To Reproduce**
1. Do nothing.
2. Chill and relax.
3. Hear drum intro of the call.
4. Loose your shit all of a sudden.
5. PROFIT.

**Expected behavior**
Something, that will attract attention, but will not cause heart attack for my pet canary.

**Comment by vbajs** [comment]
It's the original rare remix form Discord themselves, all lightcord does is enable it as the default ringtone.

You can disable it by going to settings > lightcord settings and disable calling ring beat

**Comment by NelOxingale** [comment]
> 
> 
> It's the original rare remix form Discord themselves, all lightcord does is enable it as the default ringtone.
> 
> You can disable it by going to settings > lightcord settings and disable calling ring beat

Thank you, I somehow totally missed it. Was already planning to make some asset replacement, but wasn't able to do them yet.
