### ISSUE TITLE
[BUG] Cancel button not properly closing pop-up

### ISSUE THREAD

**Issue by cabaleirog** [Lightcord/Lightcord#15]
**Describe the bug**
Cancel button doesn't seem to work on an **Allow Access** pop-up screen.

_Details:_
Just installed the app; while looking around I got to the config tab and saw "Not connected to DiscordServers.com"; proceed to click on the **Connect** button and got the pop-up to grant permission; however, was unsure I wanted to do so, and went to click on **Cancel**, which just triggered the pop-up to close and open again; only way I was able to close it was doing ALT+F4. Not a big deal, but guess not as intended.

**To Reproduce**
1. Click the **Public** button below the **Home** icon
2. Click on **Connect** right next to "Not connected to DiscordServers.com", if present.
3. Scroll down to the bottom of the pop-up and click on **Cancel**.
4. Popup will close and instantly open again, if the bug is not just on my end :)

**Expected behavior**
The pop-up should just close.

**Screenshots**
Not provided

**Desktop (please complete the following information):**
 - OS: **Manjaro Linux** 
 - Version **Rolling** [Stable]
- Desktop Environment: **Gnome 3.36.4**
- uname -r: **5.7.9-1-MANJARO**

**Additional context**
Not provided

**Comment by JeanOUINA** [comment]
We'll add a button to close the connection window, but the cancel button redirects to discordservers.com who redirect to the connection url. We can't do much on this.
