### ISSUE TITLE
[BUG] Lightcord has discord icon stuck and not going to friends list

### ISSUE THREAD

**Issue by BlueTheCircley** [Lightcord/Lightcord#150]
**Describe the bug**
This bug has been on my nerves because whenever I logged in with my 2FA, it's not working.

**To Reproduce**
1. Have Mac OS 10.14
2. Install Nightcord and log your account with 2FA
3. See the issue.

**Expected behavior**
It's expected the discord icon in the middle of the screen stuck, and will not load to friends list.

**Screenshots**
<img width="938" alt="Screen Shot 2021-01-06 at 5 48 53 PM" src="https://user-images.githubusercontent.com/60414668/103827761-b5ec6280-5047-11eb-8b73-2629d493c07b.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 10.14

**Comment by JeanOUINA** [comment]
Mac support is considered experimental, and probably won't work since I can't test as I don't have a mac.
