### ISSUE TITLE
[BUG] Lightcord not even starting up

### ISSUE THREAD

**Issue by InfernoGamingYT** [Lightcord/Lightcord#151]
**Describe the bug**
Not sure if its even a bug or just something wrong with my pc and my files, but right after installing lightcord, if i try to open the app, its just a blurry box, it doesnt change or anything, just sits there, even after it auto opens right after installation.

**To Reproduce**
I have no clue how to reproduce this, all i do is i install it, it auto-opens, blurry box
ive tried closing out of that, re-opening it, same thing, reinstalling it, same thing, ive tried getting rid of lighty's BD files on my regular BD, same thing, tried uninstalling discord then reinstalling it and uninstalling better discord, same thing

**Expected behavior**
To open the app and let me log into discord

**Screenshots**
https://imgur.com/a/W6keElS
https://imgur.com/a/GWVRgCT

**Desktop (please complete the following information):**
 -OS Windows 10
 - Version v0.1.4(the latest)

**Comment by 9zz** [comment]
cool
![Z7yljyRRBnib](https://user-images.githubusercontent.com/76086565/103945254-e7763400-5102-11eb-81dd-151f9c0e1140.gif)

**Comment by smartfrigde** [comment]
Do you have like any themes in themes folder like glasscord?

**Comment by InfernoGamingYT** [comment]
> Do you have like any themes in themes folder like glasscord?

In the actual betterdiscord themes folder? or Lightcord_BD, either way, i dont have it in either, i have lightys message logger and something else in my ACTUAL better discord folder

**Comment by JeanOUINA** [comment]
delete lighty's plugins
