### ISSUE TITLE
[Shit post] virus

### ISSUE THREAD

**Issue by k6d** [Lightcord/Lightcord#152]
virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus virus

**Comment by vbajs** [comment]
Please refer to the following
https://github.com/MessageLoggerBD/MessageLogger/issues/88

**Comment by smartfrigde** [comment]
Bruh y'all shitposting here

**Comment by JeanOUINA** [comment]
virusvirusvirusvirus

**Comment by B0wfar** [comment]
![bingus_flushed_512x512](https://user-images.githubusercontent.com/68670040/106330179-65cc7e80-6248-11eb-888e-39c2aa5bc172.jpg)
_**BINGUS!!**_

**Comment by 8uX** [comment]
lightcord is bingus virus rat logger token virus bingus

![](https://cdn.discordapp.com/attachments/767059815221428224/797371251848511488/Z7yljyRRBnib.gif)

**Comment by B0wfar** [comment]
lightcord is cum virus logger :(
![Screenshot_242](https://user-images.githubusercontent.com/68670040/106331850-42ef9980-624b-11eb-83c9-643e8eecb8dd.png)

**Comment by B0wfar** [comment]
stfu gmail

**Comment by 8uX** [comment]
stfu email

**Comment by smartfrigde** [comment]
H

pt., 29 sty 2021, 23:31 użytkownik Syz <notifications@github.com> napisał:

**Comment by B0wfar** [comment]
not cool bro

![Uploading cat-monkey.gif…]()

**Comment by 8uX** [comment]
ty lightcord for deleting that no no picture

**Comment by 8uX** [comment]
ok I am bored I will close virus

**Comment by k6d** [comment]
113 days

**Comment by k6d** [comment]
just gonna test something <a:syzbrr:814951143527546940>

**Comment by k6d** [comment]
didn't work very sad
I will now leave this open

**Comment by JeanOUINA** [comment]
stop spamming my emails cunt

**Comment by k6d** [comment]
no

**Comment by smartfrigde** [comment]
Oui

**Comment by skinatro** [comment]
Lmao wtf is this thread

**Comment by k6d** [comment]
> Lmao wtf is this thread

shitpost
