### ISSUE TITLE
[BUG] Transparency doesn't work and scrolling artifacts appear.

### ISSUE THREAD

**Issue by sortedcord** [Lightcord/Lightcord#154]
**Describe the bug**
I am on Arch Linux right now with KDE Plasma as DE. When I run lightcord (When there are no lightcord folders in ~/.config) the blur (Glasstron) works perfectly, however, when I restart lightcord, strange glitched appear when im scrolling and it becomes buggy.

**Screenshots**
This is when I have the example blur theme on...
![Screenshot_20210109_213725](https://user-images.githubusercontent.com/37407370/104099725-ebe94b00-52c2-11eb-96bc-b9fd595ae0a3.png)
![Screenshot_20210109_213829](https://user-images.githubusercontent.com/37407370/104100129-09b6b000-52c3-11eb-9421-10c383948755.png)

**Desktop (please complete the following information):**
 - OS: KDE Plasma [Arch Linux]

**Additional context**
This gets fixed once I delete the Glasscord folders in the .config directory

**Comment by JeanOUINA** [comment]
try enabling the `no window bounds` option, and if that doesn’t work, try revoking write permissions of file ~/.config/lightcord/settings.json and replace everything

**Comment by JeanOUINA** [comment]
exact steps: 
![ECAF5760-ED31-49BD-90AF-998492371C24](https://user-images.githubusercontent.com/50077294/104102760-a3b83180-529e-11eb-8bad-f6f168b47e11.jpeg)

**Comment by sortedcord** [comment]
That worked. Thanks!
