### ISSUE TITLE
I'm probably being an idiot, but I can't uninstall Lightcord.

### ISSUE THREAD

**Issue by ControlAlternateDelete** [Lightcord/Lightcord#156]
**To Reproduce**
1. Go to Start
2. Click on Lightcord
3. Scroll down to Uninstall
4. Try to look for Lightcord in Control Panel. You can't find it.

**Expected behavior**
You should be able to find Lightcord.

**Screenshots**
![image](https://user-images.githubusercontent.com/73121484/104319283-8f5f7900-54d8-11eb-8403-b68906fef650.png)

**Desktop (please complete the following information):**
 - OS: Windows
 Version: 20H2

**Comment by vbajs** [comment]
The installer for lightcord doesn't install at `C:\Program Files (x86)`, nor add lightcord to the program list

For you to uninstall lightcord, you'll have to manually delete the following folders
`%localappdata%\Lightcord`
`%appdata%\Lightcord`
`%appdata%\Lightcord_BD` (Keep this one if you want to keep your plugins and themes)

**Comment by SomeRandomArman** [comment]
it did not worked pls help me
