### ISSUE TITLE
Mcafee, Windows Defender detect it as a virus.

### ISSUE THREAD

**Issue by xXTgamerXx** [Lightcord/Lightcord#160]
![image](https://user-images.githubusercontent.com/72494265/104733633-fee99880-5764-11eb-9ffe-7ab94fa7f9a9.png)
Im not the greatest at tech but hte title explains it. I dont have my own pc and i dont want to damage my parents'...

**Comment by GermanBread** [comment]
Lightcord is safe to install. I doubt that FOSS (free and open source software) will behave in a malicious way. 
In this case make sure to allow LC through your anti-virus, as AVs like to tag LC as Malware.

**Comment by xXTgamerXx** [comment]
ok thanks im using it

**Comment by xXTgamerXx** [comment]
Can something be done about this? Its annoying that it randomly stops sometimes.

**Comment by Titaniumtown** [comment]
That's an issue with you using an anti-virus, not an issue with Lightcord.
