### ISSUE TITLE
[BUG] Clicking into Plugins or Themes makes Lightcord crash.

### ISSUE THREAD

**Issue by Exitiumundos** [Lightcord/Lightcord#161]
**Describe the bug**
Clicking into Plugins or Themes makes Lightcord crash.

**To Reproduce**

1. Click into plugins or Themes

**Expected behavior**
Clicking on either goes into its respective settings menu 

**Desktop**

- Arch Linux

-  v0.1.4 (latest AUR version)

**Comment by GermanBread** [comment]
Did you try the install script?
Also what AUR version? -git or -bin?
Did you upgrade recently?

**Comment by GermanBread** [comment]
Sadly I've not been able to reproduce this.
Can you provide us with a screenshot of errors in the console?
