### ISSUE TITLE
[FEATURE] Send emotes as link

### ISSUE THREAD

**Issue by sh5x5j12** [Lightcord/Lightcord#162]
**Is your feature request related to a problem? Please describe.**
Non nitro users can't send emotes from other servers.

**Describe the solution you'd like**
With a option users can switch between legacy and send emote as link, after that when clicking emote it will write link instead of emoji name

**Describe alternatives you've considered**

**Additional context**
Bluecord has same feature tho.

**Comment by smartfrigde** [comment]
There's already plugin for that.

**Comment by sh5x5j12** [comment]
> 
> 
> There's already plugin for that.

which plugin is it? I searched before

**Comment by JeanOUINA** [comment]
https://github.com/An00nymushun/DiscordFreeEmojis
