### ISSUE TITLE
[BUG] False positive 0BDFDB.plugin.js

### ISSUE THREAD

**Issue by Z0pyrus** [Lightcord/Lightcord#166]
False positive accrues while installing plugins which needs the library 0BDFDB.plugin.js to function.

By installing Plugins from https://github.com/mwittrien/BetterDiscordAddons , you'll need to download a Library which gets marks as "This plugin might be dangerous (Account Stealer/Virus)."

![image](https://user-images.githubusercontent.com/67390601/105184571-c7496a80-5b2f-11eb-9917-b70a59941b62.png)

This will make the plugins unusable.

 - OS: Windows 10
 - Lightcord Version: v0.1.4

**Comment by smartfrigde** [comment]
Just disable plugin scanning 🤪

**Comment by Z0pyrus** [comment]
But, which information is used to mark the program as a virus?

**Comment by smartfrigde** [comment]
Breh I think it was pluginCertifier.js

**Comment by Z0pyrus** [comment]
I know, but I'm not as smart as you may think, I understand that hash's are createt, but i dunno what happends afterwards

**Comment by Burkino** [comment]
the plugin certifier pretty much just scans every plugin file for strings such as "token"

**Comment by Z0pyrus** [comment]
If that would be true, no plugin should get marked: https://github.com/mwittrien/BetterDiscordAddons/search?q=token 
(these are basically all plugins. and some got the false positive)

**Comment by smartfrigde** [comment]
I can be wrong but I think algorithm used was Regex?

**Comment by kimberly990** [comment]
This is still an issue

**Comment by Fround1** [comment]
dont use 0BDFDB, the creator acts like a child and sends this warning so people will switch discord [Proof](https://i.imgur.com/oWMilAj.png)

**Comment by JeanOUINA** [comment]
> dont use 0BDFDB, the creator acts like a child and sends this warning so people will switch discord [Proof](https://i.imgur.com/oWMilAj.png)

Isn't that from Lighty ?

**Comment by Fround1** [comment]
> 
> 
> > dont use 0BDFDB, the creator acts like a child and sends this warning so people will switch discord [Proof](https://i.imgur.com/oWMilAj.png)
> 
> Isn't that from Lighty ?

[nope](https://i.imgur.com/xqinTKe.png)

**Comment by JeanOUINA** [comment]
oof

**Comment by vbajs** [comment]
> oof

Have you ever seen both Lighty and DevilBro in the same room 😳

**Comment by andmagdo** [comment]
I understand I am bumping this, but because of my use of devilbro's plugins and popularity of them, I forked his repo, reverted the commit ["fuck lightcord"](https://github.com/mwittrien/BetterDiscordAddons/commit/e481f645747e32634ef919f26eb661dcdda3c274), removed the warning and updated the plugins to the newest version. My repo can be found [here.](https://github.com/andmagdo/LightcordAddons)
