### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AiryXV** [Lightcord/Lightcord#167]
**Describe the bug**
When you use LightCord tabs Your discord scaling resets
**To Reproduce**
1. Go to 'LightCord Settings'
2. Click on 'Light Cord tabs'
3. See error - everytime you open up dms it will rescale back to 100

**Expected behavior**
this should not happen

**Screenshots**
cant

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 0.1.4

**Additional context**

**Comment by smartfrigde** [comment]
Lightcord Tabs are really buggy. I recommend disabling them.
