### ISSUE TITLE
[BUG] Member list doesn't work with bot account

### ISSUE THREAD

**Issue by ledlamp** [Lightcord/Lightcord#169]
**Describe the bug**
This must be a well-known issue, but there ought to be an issue open for it and surprisingly I couldn't find any. I assume bot account support is work-in-progress, but I know that bots have the ability to get member information so it should be possible to get it working.

**To Reproduce**
1. Log in with bot token
2. See member list not loading

**Expected behavior**
I want member list to work :c 

**Screenshots**
![](https://erwl.qonq.gq)

**Desktop (please complete the following information):**
Stable 75395 (e4061ca)
Lightcord 0.1.4 (a205515)
BBD 0.3.5 (lightcord)
Host 0.0.308
Windows 10 64-Bit (10.0.19042)

**Additional context**
Using a bot account is a fucking fantastic idea which I had a while ago but couldnt be arsed of even starting on what would probably be a lot of work to make my own custom client or modify the discord client. But I am so happy to have found Lightcord, it's almost perfect and exactly what I wanted. The missing member list is the only major issue.

**Comment by smartfrigde** [comment]
![image](https://user-images.githubusercontent.com/37928912/107023727-51880480-67a7-11eb-86f3-0031511bb254.png)
I think you need to turn this on in your bot settings.

**Comment by ledlamp** [comment]
> ![image](https://user-images.githubusercontent.com/37928912/107023727-51880480-67a7-11eb-86f3-0031511bb254.png)
> I think you need to turn this on in your bot settings.

Hmm, I turned off both intents but it still doesn't work.

**Comment by smartfrigde** [comment]
You have to turn them on bruh

**Comment by ledlamp** [comment]
They were on

**Comment by Picoseconds** [comment]
> You have to turn them on bruh
@smartfrigde No, bots use another intent that doesn't include the "groups" that users see.

**Comment by smartfrigde** [comment]
Ok

**Comment by Cormanz** [comment]
This is still a problem, can you guys fix it?

**Comment by smartfrigde** [comment]
Not possible afaik

**Comment by ledlamp** [comment]
How is this not possible? Bots can access all the information needed for it.

**Comment by smartfrigde** [comment]
None of bot clients available (including lightcord) have member list visible. It might be possible but no one did any research really

**Comment by ledlamp** [comment]
That's why this issue exists and should be open.

**Comment by smartfrigde** [comment]
Ok 🐩

**Comment by Mahdi-Noor-Hasan** [comment]
Having the same problem. **SERVER MEMBER INTENT** is turned on.

**Comment by bettydreemurr** [comment]
lightcord is ded

**Comment by JeanOUINA** [comment]
> None of bot clients available (including lightcord) have member list visible. It might be possible but no one did any research really

I did some research a while ago, somehow a user account uses opcode 14 to fetch members, and a bot account uses opcode 11. The opcode 14 has way more functionnalities, and it’s not worth the time fixing the member list.

**Comment by JeanOUINA** [comment]
It’s a limitation at Discord, we can’t do it without restricting bots to have the intent and to fetch every member, or to heavily change the way the client operates but still have some caveats. And it’s not worth our time to deeply change how discord’s client works.
