### ISSUE TITLE
[BUG] Lightcord laggy when moving tab around

### ISSUE THREAD

**Issue by evapey** [Lightcord/Lightcord#170]
**Describe the bug**
When I drag Lightcord around my screen it lags and it also lags other applications but if I minimise Lightcord everything is smooth again. [EDIT] It seems to only lag my other applications when it is open on the opposing monitor

**To Reproduce**
1. Drag Lightcord around your screen

**Expected behavior**
For it to be smooth when I drag it around

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version  10.0.18363 Build 18363

**Comment by JeanOUINA** [comment]
It’s a windows bug with the acrylic filter for transparent backgrounds. Try changing it to blurbehind in settings, or simply disable glasstron.

**Comment by AidanSpeakss** [comment]
> 
> 
> It’s a windows bug with the acrylic filter for transparent backgrounds. Try changing it to blurbehind in settings, or simply disable glasstron.

Is it possible for you to fix this bug? The filter itself looks great.
