### ISSUE TITLE
[BUG] Betterdiscord integration not working.

### ISSUE THREAD

**Issue by mikitr** [Lightcord/Lightcord#175]
**Describe the bug**
There is no BetterDiscord preinstalled with it, also trying to open %AppData%/Lightcord_BD says that the directroy dosen't exist

**To Reproduce**
I don't know how to reproduce it, i think ti's something with the installer.

**Expected behavior**
Working BetterDiscord, and path %AppData%/Lightcord_BD existing.

**Desktop (please complete the following information):**
 - Stable 75681 (e4061ca)
 - Lightcord 0.1.4 (a205515)
 - Host 0.0.308
 - Windows 10 64-Bit 1909 (10.0.18363)

**Comment by smartfrigde** [comment]
Fixed
