### ISSUE TITLE
Won't open under root

### ISSUE THREAD

**Issue by fluffyloopy** [Lightcord/Lightcord#176]
Exiting compilation
[26510:0203/171417.307882:FATAL:electron_main_delegate.cc(254)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

**To Reproduce**
1. cd Lightcord-master
2. npm test

**Expected behavior**
lightcord to start

**Desktop (please complete the following information):**
 - OS: ArchlinuxARM 
 - Version: latest

**Comment by smartfrigde** [comment]
First Lightcord will not work on arm. Second of all you need to install very specific version of Electron to even get loading screen(it loads infinitely). Only way to get Discord on arm is [https://github.com/SpacingBat3/electron-discord-webapp](Electron Discord Webapp)
