### ISSUE TITLE
[BUG] Some Plugins Not Working

### ISSUE THREAD

**Issue by TheMongoloid** [Lightcord/Lightcord#182]
All you do is open it and poof it pops up.
5 of my plugins don't seem to be working as whatever this is isn't working... I've looked around on here + Other forums for fixes or of any hint leading towards why it's doing it and I'm clueless

Version - 10.0.18363 Build 18363 (1909)

![2PWCqdGBP7](https://user-images.githubusercontent.com/78914154/107643681-644e7d80-6c6e-11eb-85db-43fc33c9b3a7.png)
![aohskoppZN](https://user-images.githubusercontent.com/78914154/107643683-644e7d80-6c6e-11eb-84ce-64eef876d46c.png)

**Comment by smartfrigde** [comment]
Disable plugin scanning.

**Comment by NotelessNerd** [comment]
Something that simple fixed it... Thank you boss you're the man
