### ISSUE TITLE
[BUG] Can't Edit Plugins

### ISSUE THREAD

**Issue by TheMongoloid** [Lightcord/Lightcord#183]
I can't edit plugins at all for whatever reason and a plugin called 'MessageLoggerV2' doesn't seem to be working at all for me in it.
Any help would be great :)

**Comment by GermanBread** [comment]
I will quote myself (you can see this pinned in #support):

> Lighty made their plugins not work under Lightcord. Plus you won't get any support about Lighty's plugins.

**Comment by NotelessDumb** [comment]
Oh.... That's strange but thank you for the reply

**Comment by NullCode13** [comment]
I mean you could try this:
https://gitdab.com/hana/lightcock
This seems to be some of Lighty's stuff but "supposedly" the anti-lightcord shiz have been removed

I'm havin the same prob as you and I'm lookin at possible workarounds like symlinking

**Comment by NotelessDumb** [comment]
> I mean you could try this:
> https://gitdab.com/hana/lightcock
> This seems to be some of Lighty's stuff but "supposedly" the anti-lightcord shiz have been removed
> 
> I'm havin the same prob as you and I'm lookin at possible workarounds like symlinking


I will look into that too. Thank you :)
