### ISSUE TITLE
[SMALL PROBLEM] Lower quality than normal Discord

### ISSUE THREAD

**Issue by Nermal242** [Lightcord/Lightcord#186]
I have multiple Discord clients open, including Lightcord, when comparing Lightcord with Discord, Lightcord seems like to have a lower quality of overall UI like text, avatars etc.

**Comment by smartfrigde** [comment]
Do you mean it's more blurry or is it more pixelated? Also, on what OS are you running Lightcord?

**Comment by Nermal242** [comment]
> Do you mean it's more blurry or is it more pixelated? Also, on what OS are you running Lightcord?

It's more blury and I use Windows 10 for Lightcord.

**Comment by smartfrigde** [comment]
![image](https://user-images.githubusercontent.com/37928912/108336463-5a7bcb80-71d4-11eb-805d-cbf99f8790af.png)
Try playing with these settings. They should be called "Change high resolution DPI settings" or something similar

**Comment by Nermal242** [comment]
> ![image](https://user-images.githubusercontent.com/37928912/108336463-5a7bcb80-71d4-11eb-805d-cbf99f8790af.png)
> Try playing with these settings. They should be called "Change high resolution DPI settings" or something similar

Tried both of these settings but it still is blury
