### ISSUE TITLE
[BUG] Mac version freezes when attempting to log in

### ISSUE THREAD

**Issue by halian** [Lightcord/Lightcord#191]
**Describe the bug**
Under Big Sur, the Mac version freezes at the immediate-post-login screen (with the Discord logo and fun facts about the platform) when attempting to log in. After a while, CleanMyMac will show “Lightcord Helper (Renderer)” as having frozen, and offer to kill it.

**To Reproduce**
1. Open program
2. Log into Discord
3. _Or_ open Lightcord after having logged in

**Expected behavior**
The expected behavior is Lightcord sitting on this screen for about a second, followed by transitioning to the main chat scene.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS 11.2.1 “Big Sur”
 - Version 0.1.4

**Additional context**
N/A

**Comment by JeanOUINA** [comment]
Mac support is considered experimental, and probably won't work since I can't test as I don't have a mac.
