### ISSUE TITLE
[BUG] Blurring outside of Lightcord window

### ISSUE THREAD

**Issue by bigteefcat** [Lightcord/Lightcord#193]
**Description**
On Lightcord in fullscreen, there's blurring on the edge of it that shows up on my second monitor.
I have this issue with and without various themes and plugins.
I'm

**Expected behavior**
No blur bleeding to my other monitor.

**Desktop**
 - OS: Windows 10 20H2 (10.10.19042)
 - Ver: 0.1.4 of Lightcord

**Screenshots**
![dickord](https://user-images.githubusercontent.com/79027592/108863981-60e4bb80-75b7-11eb-82f3-1a142e3da7ad.jpg)
![dickord2](https://user-images.githubusercontent.com/79027592/108863984-617d5200-75b7-11eb-881d-c03fea79316f.jpg)

**Comment by JeanOUINA** [comment]
disable glasstron in betterdiscord settings

Le mar. 23 févr. 2021 à 16:14, bigteefcat <notifications@github.com> a
écrit :

**Comment by bigteefcat** [comment]
That fixed it, thanks.
