### ISSUE TITLE
[BUG]When I try to load lightcord with Xenolib, it crashes. 

### ISSUE THREAD

**Issue by jaydenflinn** [Lightcord/Lightcord#194]
When I try to load Lightcord with Xenolib, it crashes everytime. I am never able to load in. I just want to use messagelogger with my Lightcord.

**Comment by NotelessDumb** [comment]
Xenolib crashes on lightcord and Lighty made their plugins not work under Lightcord. Plus you won't get any support about Lighty's plugins. (Light is the DEV of 'MessageLogger'
