### ISSUE TITLE
[FEATURE] Add a wiki page of docs on how to develop plugins for Lightcord.

### ISSUE THREAD

**Issue by AxDSan** [Lightcord/Lightcord#196]
**Is your feature request related to a problem? Please describe.**
I want to develop plugins for Lightcord but don't know where to get started.

**Describe the solution you'd like**
A wiki page or a dedicated docs page.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by doggybootsy** [comment]
https://github.com/rauenzi/BetterDiscordApp/wiki/Creating-Plugins
