### ISSUE TITLE
[FEATURE] Please remove JavaScript and Electron glow.

### ISSUE THREAD

**Issue by AestheticalZ** [Lightcord/Lightcord#197]
**Is your feature request related to a problem? Please describe.**
JavaScript is extremely glowy and should be obliterated in desktop applications.

**Describe the solution you'd like**
Rewrite this in C or C++ like a normal human person.

**Describe alternatives you've considered**
C, C++, V, and more languages.

**Additional context**
Massive RAM usage.

**Comment by vbajs** [comment]
No.
Lightcord is **a client mod of the official Discord cilent** not a 3rd party alternative of the official Discord cilent.

Go use non-electron based cilents such as
[discord-qt](https://github.com/ruslang02/discord-qt) or [ripcord](https://cancel.fm/ripcord/) if you want less ram usage.

**Comment by BobIsMyManager** [comment]
So lightcord is a mod, not a separate client, yet one of your selling points is the fact that you use a different .exe?

**Comment by smartfrigde** [comment]
It's mod and separate client at the same time. It takes Discord files mods them and releases that's how it works!

**Comment by BobIsMyManager** [comment]
Would be better if it wasn't tho

**Comment by vbajs** [comment]
> Would be better if it wasn't tho

Then don't use Lightcord. Especially the rewrite.

**Comment by BobIsMyManager** [comment]
What, is the rewrite gonna use even more recourses?

**Comment by smartfrigde** [comment]
Yeah including Electron we ship bitcoin miner for devs to feed families xoxo

**Comment by BobIsMyManager** [comment]
Dude, do atherium lol

**Comment by smartfrigde** [comment]
hello vbajs email box :trollface:

**Comment by BobIsMyManager** [comment]
Pog
