### ISSUE TITLE
Cant open on Linux

### ISSUE THREAD

**Issue by onigiri47** [Lightcord/Lightcord#201]
Every time I open Lightcord it closes right after a few seconds. Do you know what I should do?

**Comment by Titaniumtown** [comment]
Send logs

**Comment by JeanOUINA** [comment]
Please add more informations

**Comment by GermanBread** [comment]
Well for once you could run Lightcord in a terminal i.e. by just running `lightcord` in terminal.

Maybe that'll provide some more info.
