### ISSUE TITLE
[BUG] Lightcord not showing anything at startup.

### ISSUE THREAD

**Issue by MiRw3b** [Lightcord/Lightcord#205]
So, i just updated lightcord right now, and now it doesn't loads anything. but it opens instead the developer tools.

![image](https://user-images.githubusercontent.com/60517683/110539453-8e884380-8125-11eb-9f41-2bf638efcdfe.png)
it looks like that when i open lightcord.

I tried to uninstall and reinstall lightcord but it still does the same.

**Comment by MiRw3b** [comment]
welp i fixed it by installing it for user only 
**But now other problem; i still don't see the plugins & etc so its like a normal discord** (i used the express script so idk if its the problem or not)

**Comment by MegaShinySnivy** [comment]
I am also having this issue with the AUR bin package, where it is just like normal discord

**Comment by JeanOUINA** [comment]
Please wait, I fucked something in the release. I'll post another message when I'll finish building
