### ISSUE TITLE
[BUG] Some plugins don't work

### ISSUE THREAD

**Issue by Nermal242** [Lightcord/Lightcord#206]
Describe the bug
Some plugins won't work and gives an error, disabling Plugin Scanning won't work either. For example FriendNotifications won't work due to it shows an error when opening the settings thing on the plugins tab.
To Reproduce

Go to 'User Settings - Plugins'
Click on the settings thing for some plugins that should work in normal BetterDiscord, example FriendNotifications.plugin.
See error
Expected behavior
It should open up a settings popup and it should work.
Screenshots
image
![image](https://user-images.githubusercontent.com/56689711/110540396-bf1cad00-8126-11eb-8096-b8a3b665e677.png)
![image](https://user-images.githubusercontent.com/56689711/110540365-b6c47200-8126-11eb-9165-35a344655887.png)

Desktop (please complete the following information):

OS: Windows 10
Version 20H2

**Comment by extremegrief1** [comment]
Is it made by Lighty

**Comment by Nermal242** [comment]
> Is it made by Lighty

What do you mean?

**Comment by extremegrief1** [comment]
Who made the plugin

**Comment by extremegrief1** [comment]
Lighty blocks lightcord usually

**Comment by Nermal242** [comment]
> Who made the plugin

It happens on multiple plugins.

**Comment by Nermal242** [comment]
> Lighty blocks lightcord usually

In the screenshot it is made by DevilBro.

**Comment by vbajs** [comment]
> 
> 
> > Lighty blocks lightcord usually
> 
> In the screenshot it is made by DevilBro.

Update lightcord.
Please wait until a new update is released. do not use the new verison

**Comment by Nermal242** [comment]
> > > Lighty blocks lightcord usually
> > 
> > 
> > In the screenshot it is made by DevilBro.
> 
> Update lightcord.
> Please wait until a new update is released. do not use the new version

Yeah btw I got a new bug which makes Lightcord act just like normal Discord without BetterDiscord and Lightcord settings.
