### ISSUE TITLE
[BUG] Lightcord blocking installation of better discord plugin library

### ISSUE THREAD

**Issue by SparkizX** [Lightcord/Lightcord#210]
Lightdiscord is blocking installation of better discord plugin library

**Desktop (please complete the following information):**
 - OS: OpenSuse
 - Version: Tumbleweed
![image](https://user-images.githubusercontent.com/18197204/110682220-fc427700-81da-11eb-8201-7c283f11f66c.png)

**Comment by vbajs** [comment]
Disable Plugin scanner at settings>BetterDiscord settings.

**Comment by SparkizX** [comment]
Okay, that fixed it.
