### ISSUE TITLE
Lightcord opens without BD

### ISSUE THREAD

**Issue by DinoTymo** [Lightcord/Lightcord#213]
When opening Lightcord, Betterdiscord isn't always starting. Then you have to _Quit Lightcord_ and open it again.
Sometimes even that doesn't work, so you have to repeat it all the time.

**Comment by JeanOUINA** [comment]
Can you specify the version of Lightcord you're using ? this can be found at the bottom of the settings sidebar.

**Comment by LeSnake04** [comment]
If you have version 0.14, lightcord fails to start. Plese update to 0.15 to fix

**Comment by C0D3-M4513R** [comment]
> Can you specify the version of Lightcord you're using ? this can be found at the bottom of the settings sidebar.

v.0.1.4 can confirm

> If you have version 0.14, lightcord fails to start. Plese update to 0.15 to fix

See #214.

**Comment by kbos-vhs-2004** [comment]
im using 0.15 and the bd thing happens to me. bd doesnt even show up at all. what can i do?

**Comment by kbos-vhs-2004** [comment]
> 
> 
> im using 0.15 and the bd thing happens to me. bd doesnt even show up at all. what can i do?

fyi it works now i just gotta reinstall the stuff
