### ISSUE TITLE
[FEATURE] Improved branching and normal commit messages

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [Lightcord/Lightcord#217]
Probably the most appropriate way to start this issue is with the word "bruh"

Bruh.. I was packaging this application so people could actually use it, wanted to see what kind of changes were made so of course, I checked commits - and fuck is this
![image](https://user-images.githubusercontent.com/23264966/111517052-50aaa100-875d-11eb-8000-8bdb9822b8ba.png)

Please consider writing meaningful commit messages of some sort. 
Usually, people do something along the lines of `<action> <what>` for example: 
"Fix some bug"
"Update some awesome dependency"
"Remove unused code"

And I'd love to see master (or some other branch) represent the latest release of this application - It makes keeping track of versions and updating application packages so much easier

**Comment by Bobbbay** [comment]
![image](https://user-images.githubusercontent.com/49123594/111518618-9ef37c00-872c-11eb-9a0c-b19db0cdb438.png)
![image](https://user-images.githubusercontent.com/49123594/111518439-72d7fb00-872c-11eb-80c0-7437d5763ead.png)

Hahaha, this is not-so-professional :smile:

**Comment by papycochon** [comment]
sex

**Comment by papycochon** [comment]
>And I'd love to see master (or some other branch) represent the latest release of this application - It makes keeping track of versions and updating application packages so much easier
master is the always the latest version

**Comment by papycochon** [comment]
sex

**Comment by papycochon** [comment]
sex

**Comment by papycochon** [comment]
i love big chungus

**Comment by gytis-ivaskevicius** [comment]
> master is the always the latest version

I mean the latest **release**, not the latest version. And it does not have to be necessarily named `master`, can be anything. I just would like to see "lastest **release** branch concept"

**Comment by papycochon** [comment]
> > master is the always the latest version
> 
> I mean the latest **release**, not the latest version. And it does not have to be necessarily named `master`, can be anything. I just would like to see "lastest **release** branch concept"

it is ?

**Comment by Bobbbay** [comment]
... it's not ...

Release `0.1.5` is from 8fa4c05999d0095b188f82c5954d672501dc762f (see [here](https://github.com/Lightcord/Lightcord/tree/0.1.5)), while the latest commit on master is 49118eaac0dd653dd47415bb6a4ee3e9035a40e2.

**Comment by papycochon** [comment]
ah yeah, ok

**Comment by pryme-svg** [comment]
You can always checkout a tag

**Comment by GermanBread** [comment]
> Please consider writing meaningful commit messages of some sort
<img src="https://en.meming.world/images/en/thumb/a/a3/We_Don't_Do_That_Here.jpg/300px-We_Don't_Do_That_Here.jpg">

**Comment by gytis-ivaskevicius** [comment]
Welp, there is probably only one way for me to respond to this..... Ahem.
yall gae

**Comment by GermanBread** [comment]
agre
