### ISSUE TITLE
[BUG] AUR package doesn't build

### ISSUE THREAD

**Issue by pryme-svg** [Lightcord/Lightcord#218]
[log.txt](https://github.com/Lightcord/Lightcord/files/6168461/log.txt)

```
Error: Cannot find module 'cross-spawn'
```

While building the AUR package. However, lightcord builds when manually cloning and running npm. Build log attatched above

**Comment by Valmar33** [comment]
The AUR package does

    npm run devInstall
    npm run build

while the official instructions state

    npm run devInstall
    npm test

I get build failures for both... though different errors:

AUR package build error: https://invent.kde.org/-/snippets/1577

Manual compile build error: https://invent.kde.org/-/snippets/1578

**Comment by JeanOUINA** [comment]
This looks like a problem with NPM. Try using node 12 with npm 6.12.0

**Comment by C0D3-M4513R** [comment]
See Also #214

**Comment by Valmar33** [comment]
> This looks like a problem with NPM. Try using node 12 with npm 6.12.0

Sorry for the late reply ~ am compiling now. Will let you know if it works.

**Comment by Valmar33** [comment]
Yep, that worked!

    valmar  …  AUR  Lightcord  lightcord-git  npm -v
    6.14.12
    valmar  …  AUR  Lightcord  lightcord-git  node -v
    v12.22.0

**Comment by AkechiShiro** [comment]
I solved the issue, if anyone is using Node Version Manager (`nvm`), it seemed easy to me, the quick workaround is : 

```
nvm use v12.0.0  
npm -v
Now using node v12.0.0 (npm v6.9.0)
sudo aura -Ax lightcord-git 
# builds looks successful
```
(the option -x allow more debug information while building the AUR package).

I don't know if this issue could be fixed somehow in the AUR package because it requires the user to use a specific node and npm version (just so this issue could be closed).

**Comment by pryme-svg** [comment]
Arch has a [nodejs-lts-erbium](https://archlinux.org/packages/community/x86_64/nodejs-lts-erbium/) package which downgrades nodejs to 12.X, but no easy way to downgrade npm (without making another aur package).
