### ISSUE TITLE
[BUG] !!! Browser detects installation file as a virus !!!

### ISSUE THREAD

**Issue by JeremixxGithub** [Lightcord/Lightcord#225]
**Describe the bug**

!!! Browser detects installation file as a virus !!!

**Comment by JeanOUINA** [comment]
which browser ?

**Comment by vbajs** [comment]
Probs Edge since that's the only browser that falsely detects as a virus

**Comment by GermanBread** [comment]
<img src="https://cdn.discordapp.com/emojis/750880959242436780.png" width="100%">

**Comment by AhmadJG** [comment]
wtf how did i find you here

**Comment by vbajs** [comment]
Discordo server

**Comment by vbajs** [comment]
Email moment

**Comment by GermanBread** [comment]
email

**Comment by JeanOUINA** [comment]
anyway

**Comment by GermanBread** [comment]
**JeanOUINA** closed this *2 minutes ago*
