### ISSUE TITLE
[FEATURE] Support stereo audio

### ISSUE THREAD

**Issue by Bleuzen** [Lightcord/Lightcord#229]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when [...]
I'm streaming music over Discord and other channel members only hear it in mono.

**Describe the solution you'd like**
The client should send a stereo audio signal instead of forcing a mono one.

> Discord already supports stereo audio. Bots can use it without a problem, so do other custom clients (for example https://github.com/AAGaming00/stereo for Powercord).

The should be an optional option because maybe there are users out there enjoying the downmix to mono for their use-case.

**Describe alternatives you've considered**
An alternative is to use a bot which captures from a PulseAudio/JACK source from my machine and streams it to Discord.
While this works on my server, this is inconvenient, especially on servers of others.

**Additional context**
-

**Comment by smartfrigde** [comment]
Patched by discord

**Comment by Bleuzen** [comment]
@smartfrigde  nope, still doesn't work. Sound is still Mono.
What exactly do you mean?

**Comment by GermanBread** [comment]
Use vanilla Discord

**Comment by Bleuzen** [comment]
@GermanBread  I have. Discord stable and Discord Canary. Both are Mono only too.

**Comment by smartfrigde** [comment]
Clients can't send stereo sound. It's been patched by discord on server side

**Comment by Bleuzen** [comment]
Fml. so sad.

But thanks for the info.
