### ISSUE TITLE
[BUG] Lightcord and BD Settings Missing

### ISSUE THREAD

**Issue by KibSquib48** [Lightcord/Lightcord#232]
**Describe the bug**
The settings page is missing the lightcord and BD settings

**Screenshots**
![Screenshot_20210402_102737](https://user-images.githubusercontent.com/33189136/113424385-1288c080-939e-11eb-9e72-4fd333a81eed.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version v0.1.5 (lightcord-bin from the AUR)

**Additional context**
I tried deleting all folders related to lightcord, uninstalling lightcord, and installing it again, and that didn't work. I also tried a reboot, that didn't work either. I tried the appimage instead, also didn't work.

**Comment by GermanBread** [comment]
![uh huh](https://user-images.githubusercontent.com/71450236/113428885-e5f19a80-93d7-11eb-9b39-936febea06ce.png)

Lightcord

**Comment by GermanBread** [comment]
<img src="https://cdn.discordapp.com/emojis/503536590065369088.gif?v=1">
Did you launch Discord instead?
That does not look like Lightcord.
If it is, use lightcord-git? Or the install script?

**Comment by KibSquib48** [comment]
> If it is, use lightcord-git? Or the install script?

both lightcord-git and the install script failed to install lightcord properly

**Comment by GermanBread** [comment]
> the install script failed to install Lightcord properly

Tell me how it failed and I'll fix it ASAP.
Demonstrating the failure via a screen recording would help a lot.

**Comment by GermanBread** [comment]
You could try `mv .config/Lightcord .config/Lightcord~` and `mv .config/Lightcord_BD .config/Lightcord_BD~`

Maybe that'll do something?

**Comment by KibSquib48** [comment]
> You could try `mv .config/Lightcord .config/Lightcord~` and `mv .config/Lightcord_BD .config/Lightcord_BD~`
> 
> Maybe that'll do something?

That seems to have fixed it, the settings are all back now

> Tell me how it failed and I'll fix it ASAP (provided that it's an installer issue).
> Demonstrating the failure via a screen recording would help a lot.

here's the log for what happens when I try to install lightcord-git:
[text.txt](https://github.com/Lightcord/Lightcord/files/6250255/text.txt)

Installing with the script and then launching the appimage gives me this error:
![Screenshot_20210402_133455](https://user-images.githubusercontent.com/33189136/113439261-38bb5a00-93b8-11eb-9d44-13ddb9cc847e.png)

**Comment by GermanBread** [comment]
How about the global install (installer)?

**Comment by GermanBread** [comment]
> Installing with the script and then launching the appimage gives me this error

The AppImage is located at `~/.LightCord`
try double-clicking it?

**Comment by KibSquib48** [comment]
> How about the global install (installer)?

```
  _    _      _   _                 _
 | |  (_)__ _| |_| |_ __ ___ _ _ __| |
 | |__| / _` | ' \  _/ _/ _ \ '_/ _` |
 |____|_\__, |_||_\__\__\___/_| \__,_|
        |___/
  Unified Linux Installer and Updater

Please select
1: Install Lightcord for all users
2: Install Lightcord only for you (Appimage install)

1
==> Warning:
        Blindly running software as root is a massive security issue.
        If you don't fully trust the software you're running DON'T RUN IT AS ROOT.
        If you know exactly what you are doing, continue.
        Otherwise restart this script and choose the second option.
==> Please enter your password to proceed
[sudo] password for kibsquib48: 
==> Authentication complete
Please select
1: Install Lightcord
2: Uninstall Lightcord
3: Update Lightcord

1
==> Installing Lightcord
> Preparing
> Downloading Lightcord
[lightcord-linux-x64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of lightcord-linux-x64.zip or
        lightcord-linux-x64.zip.zip, and cannot find lightcord-linux-x64.zip.ZIP, period.
bash: line 153: cd: Lightcord: No such file or directory
chmod: cannot access './lightcord': No such file or directory
mv: cannot stat 'Lightcord/': No such file or directory
> Downloading Lightcord icon
lightcord.png: Permission denied
mv: cannot stat 'lightcord.png': No such file or directory
> Creating Desktop entry
bash: line 162: Lightcord.desktop: Permission denied
mv: cannot stat 'Lightcord.desktop': No such file or directory
> Cleaning up
```
> The AppImage is located at `~/.LightCord`
> try double-clicking it?

Nothing happens. The file also says it takes up 0B and when I open it with a text editor it's blank

**Comment by GermanBread** [comment]
About the AppImage:

The issue seems to be with Github, not the script.

> HTTP 521

5xx = Issue on servers' side

**Comment by GermanBread** [comment]
Okay so it's a Github issue then. Wait a little until the situation resolves itself...

**Comment by JeanOUINA** [comment]
If the script is using lightcord.org as a download, it is currently down.

**Comment by GermanBread** [comment]
@JeanOUINA It's using Github

**Comment by GermanBread** [comment]
523 is the status code of lightcord.org

```
<html>
<head><title>523 Origin Unreachable</title></head>
<body bgcolor="white">
<center><h1>523 Origin Unreachable</h1></center>
<hr><center>cloudflare-nginx</center>
</body>
</html>
```

**Comment by papycochon** [comment]
yes

**Comment by papycochon** [comment]
pov you closed accidentally

**Comment by DodoGames7** [comment]
is zip file portable? i just download the zip of lightcord yet
