### ISSUE TITLE
Pop-up window about Discord ToS issues

### ISSUE THREAD

**Issue by DinoTymo** [Lightcord/Lightcord#233]
Today after opening the client this popped up:
![Screenshot of pop-window](https://user-images.githubusercontent.com/64032626/114048106-8ccbb000-988a-11eb-9c2a-e18a638a3cc3.jpg) - This is the first time, I've seen something like that.

After clicking on "okay" the client crashed a few seconds later. So I opened it again and everything worked fine.

I don't know why that happened but I don't think this should happen.

**Comment by smartfrigde** [comment]
This warning is from BDFDB plugin. You can remove the warning in code. Also about the crashing, can you send what plugins you use?

**Comment by JeanOUINA** [comment]
The warning is coming from plugins from DevilBro (BDFDB, etc). The crash may be because of plugins from Lighty (MessageLogger, Xenolib, etc).
