### ISSUE TITLE
Plugin component error

### ISSUE THREAD

**Issue by BorisKalashnikov** [Lightcord/Lightcord#234]
Plugin component error comes up when i try to go into the plugin's settings also it happeneds with every plugin that i tried with, and plugins that doesn't have settings on them not works either. I don't have any clue to fix this.

**Comment by vbajs** [comment]
There is no way to fix it unless @JeanOUINA updates BBD
Please switch to another discord client mod

**Comment by BorisKalashnikov** [comment]
> There is no way to fix it unless @JeanOUINA updates BBD
> Please switch to another discord client mod

okay thanks for fast response

**Comment by smartfrigde** [comment]
Fixed by latest commits. Either build from source or wait for new release
