### ISSUE TITLE
[FEATURE] Betterdiscord 1.0

### ISSUE THREAD

**Issue by ribkix** [Lightcord/Lightcord#235]
**Is your feature request related to a problem? Please describe.**
Lot's of plugins are not working anymore due to the fact Lightcord is still making use of BandagedBD. Please move to the new Betterdiscord version.

**Describe the solution you'd like**
Move to the new Betterdiscord version (https://github.com/rauenzi/BetterDiscordApp/releases)

**Describe alternatives you've considered**
There are no alternatives to this.

**Additional context**
Lot's of plugins just don't work, and cool changes are missing.

**Comment by vbajs** [comment]
> **Describe alternatives you've considered**
> There are no alternatives to this.

There is, which is use BetterDiscord itself.

**Comment by ribkix** [comment]
> > **Describe alternatives you've considered**
> > There are no alternatives to this.
> 
> There is, which is use BetterDiscord itself.

but it's outdated and buggy

**Comment by vbajs** [comment]
> 
> 
> > > **Describe alternatives you've considered**
> > > There are no alternatives to this.
> > 
> > 
> > There is, which is use BetterDiscord itself.
> 
> but it's outdated and buggy

Have you ever bothered to try out BetterDiscord beta?

**Comment by ribkix** [comment]
> > > > **Describe alternatives you've considered**
> > > > There are no alternatives to this.
> > > 
> > > 
> > > There is, which is use BetterDiscord itself.
> > 
> > 
> > but it's outdated and buggy
> 
> Have you ever bothered to try out BetterDiscord beta?

that's exactly what I'm talking about in this issue

**Comment by smartfrigde** [comment]
From what I know updating BetterDiscord is not as easy as replacing files with newer ones. It requires some work and devs are currently working on rewrite so yeah.

**Comment by ribkix** [comment]
> From what I know updating BetterDiscord is not as easy as replacing files with newer ones. It requires some work and devs are currently working on rewrite so yeah.

the rewrite has been finished, and it's certainly true that you can't easily just change it.

**Comment by smartfrigde** [comment]
How is it finished when last week ago only themes worked

**Comment by ribkix** [comment]
> How is it finished when last week ago only themes worked

plugins are working for me since the day I installed it

**Comment by smartfrigde** [comment]
I'm talking about Lightcord rewrite not BetterDiscord

**Comment by ribkix** [comment]
> I'm talking about Lightcord rewrite not BetterDiscord

ooo my brain must have farted there
