### ISSUE TITLE
[BUG] Acrylic makes dragging the window slow

### ISSUE THREAD

**Issue by ribkix** [Lightcord/Lightcord#236]
**Describe the bug**
When you enable Acrylic mode, when you drag the window around it duplicates your cursor and does it very slowly.

**To Reproduce**
1. Click on the gear in the bottom left with the tooltip 'User Settings'
2. Go under 'Lightcord Settings'
3. Scroll down to 'Window'
4. Change 'Glasstron Blur' to 'Acrylic'
5. Drag the window around and see what happens

**Expected behavior**
I expected the window to just have more blur (which it does) but further do nothing else, but now this problem occurs.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version 20H2 19042.906

**Additional context**
You may think it may have to do with my specifications, but it doesn't.
CPU: Ryzen 7 3700x
GPU: RTX 2060S
RAM: Corsair Vengeance 32 GB 3600mhz 4x8

**Comment by JeanOUINA** [comment]
This is a bug with Windows itself.
