### ISSUE TITLE
[BUG] BDFDB asks me politely to stop using Lightcord every time I start it

### ISSUE THREAD

**Issue by KiritoLeFakePK** [Lightcord/Lightcord#238]
**Describe the bug**
BDFDB asks me politely to stop using Lightcord every time I start it

**To Reproduce**
1. Launch Lightcord with BDFDB

**Screenshots**
![image](https://user-images.githubusercontent.com/17341929/114237111-e6170a80-9982-11eb-9383-0617f29713f0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.19042)
 - Version: Lightcord 0.1.5 (6bd9c0a)

**Comment by vbajs** [comment]
At least it asks you politely, unlike Xenolib which proceeds to brick your lightcord client

**Comment by ribkix** [comment]
the same happens to me its annoying lightcord should make a setInterval and delete the element if its there constantly

**Comment by smartfrigde** [comment]
Remove code yourself lmao
xoxo hun

**Comment by ribkix** [comment]
> Remove code yourself lmao
> xoxo hun

then its faster to just press the X since I have no experience with Discord's Javascript and Lightcord does.

**Comment by ribkix** [comment]
As a temporal fix go and edit BDFDB, and remove this chunk of code (you can find it by just searching for `window.Lightcord`):
```js
if (window.Lightcord || window.LightCord) BDFDB.ModalUtils.open(BDFDB, {
	header: "Attention!",
	subHeader: "Modified Client detected",
	text: "We detected that you are using LightCord. Unlike other Client Modificaton (BetterDiscord, PowerCord), LightCord is a completely modified Client, which is no longer maintained by Discord but instead by a 3rd Party. This will put your Account to risk, not only because the 3rd Party might do with your Account Credentials what they want, you are also breaking a higher Instance of Discord's ToS by using a 3rd Party Client instead of using a simple Client Mod. Many Plugins won't flawlessly run on LightCord. We do not support LightCord and as such, we do not provide Help or Support. You should switch to another Modification.",
	buttons: [{color: "RED", contents: BDFDB.LanguageUtils.LanguageStrings.OKAY, close: true}]
});
```

**Comment by DodoGames7** [comment]
is this message fake?

**Comment by GermanBread** [comment]
No, not fake
