### ISSUE TITLE
Discord installation flagged as corrupt

### ISSUE THREAD

**Issue by 1Michael23** [Lightcord/Lightcord#240]
**Describe the bug**
Discord displays a constant red banner warning me my discord installation is corrupted, it also doesn't let me video call and tells me im using a browser 
 

**To Reproduce**
1. use install script method to install on Linux
2. install as appimage
3. login

**Expected behavior**
being able to video call and not being harassed by discord 

**Screenshots**
![image](https://user-images.githubusercontent.com/33250781/114483735-6b572500-9bf8-11eb-8610-b9e25400a748.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 21.04 Hirsute Hippo beta

let me know if you need any logs, Im happy to send them to help fix the issue but i don't know where to find them.

**Comment by 1Michael23** [comment]
damn cant edit the title. corrupt*

**Comment by smartfrigde** [comment]
```
'libc6',
'libasound2',
'libatomic1',
'libgconf-2-4',
'libnotify4',
'libnspr4',
'libnss3',
'libstdc++6',
'libxss1',
'libxtst6',
'libappindicator1',
'libc++1'
```
Install these dependecies

**Comment by deybedanta** [comment]
> ```
> 'libc6',
> 'libasound2',
> 'libatomic1',
> 'libgconf-2-4',
> 'libnotify4',
> 'libnspr4',
> 'libnss3',
> 'libstdc++6',
> 'libxss1',
> 'libxtst6',
> 'libappindicator1',
> 'libc++1'
> ```
> 
> Install these dependecies

how do i install them?

**Comment by JeanOUINA** [comment]
`sudo apt install libc6 libasound2 libatomic1 libgconf-2-4 libnotify4 libnspr4 libnss3 libstdc++6 libxss1 libxtst6 libappindicator1 libc++1`

**Comment by GermanBread** [comment]
oddly enough Arch only has 'libnspr4.so' and 'libnss3.so'

**Comment by GermanBread** [comment]
so those two might just be enough to get rid of that error

**Comment by GermanBread** [comment]
Those issues should be obsolete once #254 gets merged
