### ISSUE TITLE
[BUG] Plugins Blocked

### ISSUE THREAD

**Issue by VezCodez** [Lightcord/Lightcord#245]
**Describe the bug**
Whenever I add a plugin, it get's blocked. (I can't use it)

**To Reproduce**
1. Go to plugins
2. Click on plusins folder
3. Add your plugin
4. See

**Expected behavior**
It should work when restarting

Windows 10 20H2
**Additional context**
Discord: Vez#0005

**Comment by GermanBread** [comment]
Disable plugin scanning in settings. Should be easy to find I hope.
