### ISSUE TITLE
I would like to use this as, like, a website. Like the web version of discord. How might I go about this?[FEATURE]

### ISSUE THREAD

**Issue by CashorCredit** [Lightcord/Lightcord#246]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GermanBread** [comment]
Good job of filling out the fields.

Bonus points for putting everything in the header.

**Comment by GermanBread** [comment]
> I would like to use this as, like, a website.

Not possible as of now. Though you might try joining the Discord server and beg the devs to 
1. Develop / publish a web version
2. Rent a VPS.

**Comment by CashorCredit** [comment]
Ok will do

**Comment by Picoseconds** [comment]
This entire app still uses the Discord website. If you want an identical experience, use discord.com

**Comment by CashorCredit** [comment]
Ok, thanks

**Comment by T-O-R-U-S** [comment]
To go about making a web version is not really much harder than just plastering the HTML + any other core pieces of code onto a web browser instead of electron. You may have to figure out some kinks with node_modules, but most build tools (e.g Vite, webpack) already handle that for you.

**Comment by CashorCredit** [comment]
Yes, but which core pieces of code are needed to make the website?

**Comment by thomasjosif** [comment]
Sounds like an easy way for discord to do a DMCA takedown on your site.

**Comment by T-O-R-U-S** [comment]
@CashorCredit core pieces are basically everything that is not electron/the raw webpage (and glasstron as well). So basically all React/Svelte/Vue code + associated CSS/JS files.

**Comment by Picoseconds** [comment]
This client uses Discord.com...

**Comment by smartfrigde** [comment]
No real way of adding BD into web app (it's possible but devs are busy working on LC rewrite ™️) if you mean that. I suggest you try out [GooseMod](https://goosemod.com). It works in browser fine and has [Chrome Extension](https://github.com/AAGaming00/GooseMod-chrome)
