### ISSUE TITLE
[BUG] Avast Free Antivirus detecting Lightcord as a virus.

### ISSUE THREAD

**Issue by todoroviclazar086** [Lightcord/Lightcord#248]
When i install Lightcord, it auto launches it.
But when it launched, it aborted it and claimed that its a virus.
Here is the screenshot.
![image](https://user-images.githubusercontent.com/77443970/115702095-cad7d200-a368-11eb-8bab-f5dc23925377.png)

**Comment by MoltenCoreDev** [comment]
Avast worked. Lightcord is obviously a virus.

**Comment by JeanOUINA** [comment]
disable avast it’s shit

**Comment by JeanOUINA** [comment]
or don’t use lightcord, it’s also shit

**Comment by GermanBread** [comment]
> or don’t use lightcord, it’s also shit

wtf!!! 💯 💯 💯 💯 💯 💯

**Comment by Gabriel-Barbosa-de-almeida** [comment]
Oh man i think that i can trust avast this time...

**Comment by bettydreemurr** [comment]
lmfao
