### ISSUE TITLE
unban 564843886434975745

### ISSUE THREAD

**Issue by Joshix-1** [Lightcord/Lightcord#25]
**Describe the bug**
564843886434975745 is banned

**To Reproduce**
1. Go to 'https://discord.com/invite/7eFff2A'
2. Login as 564843886434975745

**Expected behavior**
564843886434975745 shouldn't be banned.

**Screenshots**
![image](https://user-images.githubusercontent.com/57299889/90822217-64f7fe00-e334-11ea-8fe9-1606d8bbb4f5.png)

Desktop:
    Kernel: Linux 5.7.12-arch1-1
    Architecture: x86-64
    Lightcord version: 0.1.4

**Comment by unixkeys** [comment]
should be fixed in next release
