### ISSUE TITLE
Lightcord on Ubuntu Linux shows the corrupt installation banner[BUG]

### ISSUE THREAD

**Issue by deybedanta** [Lightcord/Lightcord#253]
**Describe the bug**
When you install Lightcord through the _sh -c "$(curl -s https://raw.githubusercontent.com/Lightcord/Lightcord/master/LULI.sh)"_ command line, when the program is ran, it shows the Corrupt Installation banner.

**To Reproduce**
1. Go to terminal.
2. Install using _sh -c "$(curl -s https://raw.githubusercontent.com/Lightcord/Lightcord/master/LULI.sh)"_
3. Run the program.
4. See error at top.

**Expected behavior**
Works like normal and no banner is shown.

**Screenshots**
https://imgur.com/a/K0o5Ck5

**Desktop (please complete the following information):**
 - OS: Ubuntu/Linux
 - Version 20.04 [Focal Fossa] GNOME

**Comment by JeanOUINA** [comment]
*Forwarded from lightcord discord server*

If you are getting installation corrupt message, make sure you have the following installed, usually `libatomic1` is the culprit
```'libc6',
'libasound2',
'libatomic1',
'libgconf-2-4',
'libnotify4',
'libnspr4',
'libnss3',
'libstdc++6',
'libxss1',
'libxtst6',
'libappindicator1',
'libc++1'```

**Comment by deybedanta** [comment]
Im trying it right now.

**Comment by GermanBread** [comment]
uhh should we put this warning in the installer?
