### ISSUE TITLE
[BUG] Black screen stuck at MacOS(M1)

### ISSUE THREAD

**Issue by Tetragromaton** [Lightcord/Lightcord#256]
**Describe the bug**

I am using MacBook Pro with M1 Chip. So there is an issue that I've downloaded latest release build from here and right after I've logged in, the Lightcord stucks at black background:
https://imgur.com/a/x8KJjXD

**To Reproduce**
1. Download latest macOS build
2. Authorize
3. You'll stuck.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.3
 - Version Latest

That's ok if Lightcord does not have Apple Silicon support yet.

**Comment by nopeinomicon** [comment]
Bug appears to be the same as #171

**Comment by T-O-R-U-S** [comment]
Could this be related to Rosetta 2, or are there native `aarch-64` builds? 🤔 It's not specified which architecture Lightcord uses, aside from "darwin"...

**Comment by AvaQueen-Official** [comment]
Please someone fix this. The last terminal output I get is "this application was not signed by Discord". Maybe that has something to do with it?

**Comment by smartfrigde** [comment]
Not related

**Comment by AvaQueen-Official** [comment]
@smartfrigde what is it then? There must be *some* fix.

**Comment by smartfrigde** [comment]
Do CTRL+Shift+I and show the logs. Lightcord is outdated af. If you want to use something that will not break randomly then use normal client mod (BBD Powercord GooseMod etc)

**Comment by AvaQueen-Official** [comment]
Ok so there's no solution to fix it then?

**Comment by smartfrigde** [comment]
Bruh

**Comment by AvaQueen-Official** [comment]
Ok, ok! I get it, no solution. Sorry for making you so angry.

**Comment by smartfrigde** [comment]
#111

**Comment by smartfrigde** [comment]
Can't be resolved.
