### ISSUE TITLE
Everytime I try to put the MessageLogger plugin in LightCord it's not working

### ISSUE THREAD

**Issue by hashs3c** [Lightcord/Lightcord#266]
I downloaded the MessageLogger V2 plugin for betterdiscord since it's already pre installed with LightCord but it's telling me that there is a virus or I don't know what and it delete's it

**Comment by smartfrigde** [comment]
sussy among us
sssss

**Comment by smartfrigde** [comment]
Lighty broke his plugins from working on Lightcord, so it's not an issue of Lightcord
Also, we'll never offer support nor any forks of his plugins that has been modified to work on Lightcord. To remove it go to %APPDATA%/Lightcord_BD/plugins and delete the file you want
xoxo
