### ISSUE TITLE
[BUG][LINUX] Pinning Lightcord to the appbar and opening it will open it, but with the Lightcord icon twice in your appbar

### ISSUE THREAD

**Issue by Simon1511** [Lightcord/Lightcord#268]
**Describe the bug**
First I wanna say that this is actually a bit hard to explain, therefore I advise you to look at the pics down below (screenshot no. 1).
So, if you pin Lightcord to the appbar and then open it, Lightcord will open, but the Lightcord icon will appear twice in your app bar.

**To Reproduce**
1. Pin Lightcord to the appbar (i.e. with Gnome desktop it would be "add to favourites")
2. Click the Lightcord icon in the appbar that you just pinned.
3. You'll have the icon twice.

**Expected behavior**
The expected behaviour should be the same as with normal Discord, i.e. the window opening in the same icon. (Screenshot no. 2)
The bug doesn't happen on Linux with normal Discord or BetterDiscord. Its also fine on Windows 10 with Discord/BetterDiscord/Lightcord.

**Screenshots**
1.
![Screenshot from 2021-05-27 15-23-45](https://user-images.githubusercontent.com/46072379/119833824-b787cb80-beff-11eb-8d1e-9f6c4bb5b9ff.png)

2.
![Screenshot from 2021-05-27 15-23-26](https://user-images.githubusercontent.com/46072379/119833850-bce51600-beff-11eb-8d87-a6a634d7b1b8.png)

**Desktop:**
 - OS: Ubuntu
 - Version 20.04.02 LTS

**Additional context**
Issue #173 seems to focus the same bug.
While taking a look at the Lightcord.desktop file, I noticed that the workaround from the referenced issue is missing on my system.
Adding the workaround from there to the file fixes it.

**Comment by GermanBread** [comment]
Is this the fix you're talking about?

`StartupWMClass=lightcord`

**Comment by Simon1511** [comment]
> Is this the fix you're talking about?

Yes, it is.



> Allright, should be fixed
> 
> just reinstall LC with the install script (update option does not replace the .desktop!)

If I understand this correctly, it was broken after updating LC? I just clean installed it and had this bug.

**Comment by GermanBread** [comment]
> If I understand this correctly, it would be broken after updating LC? I just clean installed it a few hours ago and had this bug.

It was never fixed in the first place; so nothing broke on your part.

Now it's fixed.

**Comment by Simon1511** [comment]
Ah ok, I assumed it was already fixed before because issue #173 mentions that a PR with that fix was merged.
Anyway, many thanks for the fix!

Apart from that, I just found another "bug".
If I get a message in discord, it usally has a round badge with the amount of notifications on top of the icon in the appbar.
This is also not working with LC while it's fine with normal Discord.
