### ISSUE TITLE
[BUG] Component Error

### ISSUE THREAD

**Issue by remi42000** [Lightcord/Lightcord#271]
**Describe the bug**
so when i click on setting on the plug in windows i get "Component Error"

**To Reproduce**
i install some .js plug in like word notification etc..

**Expected behavior**
show the plug-in settings correctly

**Screenshots**
If applicable, add screenshots
![bug1](https://user-images.githubusercontent.com/65598339/120777968-21b6f680-c526-11eb-9d2c-d71d3dcb4526.png)
 to help explain your problem.

**Desktop (please complete the following information):**
 - OS:popos 21.04
 - Stable 86782 (3d650d1)
Host 0.1.5
Linux 64-Bit (5.11.0-7614-Generic)

**Additional context**

**Comment by smartfrigde** [comment]
Just build from source. It was fixed a while ago but there was no release @JeanOUINA 🐩
