### ISSUE TITLE
separate clients of betterdiscord and lightcord only [FEATURE]

### ISSUE THREAD

**Issue by ZwezAbnW** [Lightcord/Lightcord#272]
**Is your feature request related to a problem? Please describe.**
yes the problem when I press relaunch without betterdiscord then I close the program and run it again it lunch it with betterdiscord and I don't want betterdiscord
**Describe the solution you'd like**
separate clients like download lighcord with betterdiscord & download lightcord (normal discord)
**Describe alternatives you've considered**
fix the issue that it always lunch it betterdiscord could also help
**Additional context**
I don't have anything else I love lightcord keep it up <3

**Comment by smartfrigde** [comment]
run with --disable-betterdiscord flag. You can add it to shortcut or something
