### ISSUE TITLE
[BUG] Account Info page crashes discord client when plugins installed

### ISSUE THREAD

**Issue by Sympthey** [Lightcord/Lightcord#274]
**Describe the bug**
Once a plugin is install and you try and go to the account info page then your discord client is going to crash.

**To Reproduce**
Install a plugin
Go to settings
Account info
Watch discord client crash

**Expected behaviour**
When it did work it would display my account information.

**Screenshots**
https://i.imgur.com/NkJdE0c.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Latest One

**Additional context**
The account info page was working fine before I install some plugins.

**Comment by k6d** [comment]
Hello Sympthey, Do you know what plugin caused lightcord to crash?

**Comment by smartfrigde** [comment]
pain


also account info is broken iirc don't use it
xoxo

**Comment by GermanBread** [comment]
It crashes the client without plugins.

Running from source might fix this though

**Comment by smartfrigde** [comment]
it won't as it was broken on rewrite too :godmode:

**Comment by Sympthey** [comment]
> Hello Sympthey, Do you know what plugin caused lightcord to crash?

I removed all plugins and it still crashes. This is weird because once I first got it installed it was working fine but now it just crashes when I go to the account info.

**Comment by smartfrigde** [comment]
It just broke after Discord changed few things. I might fix it later

**Comment by smartfrigde** [comment]
Fixed by latest release! Thanks for reporting ;)
