### ISSUE TITLE
[BUG] Multi-monitor screensharing

### ISSUE THREAD

**Issue by ShayBox** [Lightcord/Lightcord#28]
GNU/Linux - Archlinux - AUR package

So there's been a bug with discord since linux client screensharing was released which caused all monitors to be grouped together as a single monitor, discord was aware of this bug from day 1 (many years now) but recently deleted the linux bug tracker trello, so it's probably never getting fixed.

I've been making a workaround Mon2Cam to stream screens into a virtual webcam but this just a hacky workaround, This is where lightcord comes in, since discord is likely never going to do this, I was hoping this could be done in lightcord

Recently I tested the discord client using electron 9.2.x using discord_arch_electron via AUR, which changed something in electron to show individual screens in the screen share menu, but it still only shares all the screens together, so some internal change needs to be made to use the screen size variables from electron.

Screenshots:
Official Discord linux client using Electron 9
![image](https://user-images.githubusercontent.com/9505196/90976020-92e16c00-e507-11ea-86f5-fb6dff420c6b.png)

Official Discord linux client using built-in electron & Lightcord using Electron 8
![image](https://user-images.githubusercontent.com/9505196/90976033-b9070c00-e507-11ea-9608-9264cc88e4a5.png)

**Comment by D3SOX** [comment]
Additional information not mentioned above: It works perfectly fine when using Discord in the browser (using Chromium 84.0.4147.125).
I think it might be necessary to use a very recent version of Chromium and therefore also a recent version of Electron.

**Comment by Oof4** [comment]
chromonium sucks and is outdated use google man :/

**Comment by ShayBox** [comment]
Chromium is literally the base project for chrome, Google updates chromium and has a fork with closed source code that makes chromium chrome

**Comment by Oof4** [comment]
ik that

**Comment by simon511000** [comment]
We can't use chrome, discord -> electronjs > chronium

**Comment by unixkeys** [comment]
@simon511000 @Oof4 please go discuss this elsewhere, @D3SOX's remark is helpful and means that it's not coming from the OS itself/outdated software provided for it, i will now delete your comments and will proceed to ban if you do it again.

**Comment by pryme-svg** [comment]
The electron version was recently updated. Works for me now 
![image](https://user-images.githubusercontent.com/65417452/101292053-f8f5b480-37c1-11eb-8278-508e42f770f5.png)

**Comment by Donald4444** [comment]
@pryme-svg if you share one of the screen is the output only the selected screen or a combination of all?
In my case there are is still a combination of all screens shared (like the Electron 8 preview), even though the screens are showed seperatly. As far as I know that's an bug in the discord library.

**Comment by pryme-svg** [comment]
Oh yeah the stream is still multiple screens. False alarm

**Comment by papycochon** [comment]
I personally had this issue on stable when I used arch, could you check if it works on stable/ptb/canary ?

Even if it does I doubt that we will be able to fix that issue properly.

**Comment by ShayBox** [comment]
It doesn't work with any official discord client, only browsers, it's a change in discords code to use the new selected monitor variables to crop the view when screensharing, hopefully something you can do

**Comment by jonasled** [comment]
Discord released today version 0.0.15 and it looks like they fixed the bug in the official client: https://support.discord.com/hc/en-us/community/posts/1500000548361-Linux-Multiple-Monitors-Screen-share-CAN-be-fixed-easily-

**Comment by ShayBox** [comment]
Yes, this is finally officially fixed, now we just need audio sharing :+1:

**Comment by malinkb** [comment]
Running latest lightcord 1.7, I still get a combination of both screen bug/issue while sharing
