### ISSUE TITLE
[FEATURE] Different system tray icon

### ISSUE THREAD

**Issue by ImportTaste** [Lightcord/Lightcord#281]
Since I want to use Lightcord for a separate account, it would be nice if the systray icon were different.

**Comment by smartfrigde** [comment]
Find location where your Lightcord is installed (Windows is `%LocalAppdata%/Lightcord`). Then follow this path `resources/modules/discord_desktop_core/core/app/images/systemtray/` and there you will find all icons which you can manually replace.

**Comment by ImportTaste** [comment]
> Find location where your Lightcord is installed (Windows is `%LocalAppdata%/Lightcord`). Then follow this path `resources/modules/discord_desktop_core/core/app/images/systemtray/` and there you will find all icons which you can manually replace.

I didn't find anything there, but there are some loose pngs in the base `%LocalAppdata%/Lightcord` directory named tray.png, tray-connected.png, etc. I assume I can just change these?

**Comment by smartfrigde** [comment]
oh yeah I meant those
sorry for confusion I was looking at unpacked version
