### ISSUE TITLE
[BUG] Red screen instead of settings screen

### ISSUE THREAD

**Issue by SparkizX** [Lightcord/Lightcord#289]
**Describe the bug**
When you try getting into settings lightcord turns red (linux (opensuse tumbleweed) and windows confirmed)

**To Reproduce**
1. Open lightcord
2. Clicking on settings cog to open settings menu

**Expected behavior**
I expected to see settings screen instead of red screen

**Screenshots**
![image](https://user-images.githubusercontent.com/18197204/122308991-c1ed2200-cf0d-11eb-94be-04642698c8b5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Version: 19042.1052
Second OS:
- OS: OpenSuse Tumbleweed
- Version: Updated everyday

**Additional context**
None

**Comment by Dmitrisv** [comment]
Delete themes because devil bro go crazy

**Comment by SparkizX** [comment]
Where was the theme folder located?

**Comment by JeanOUINA** [comment]
%AppData%\Lightcord_BD\themes---- On jeu., 17 juin 2021 10:52:58 +0200  ***@***.******@***.***> wrote ---- 
Where was the theme folder located?

**Comment by SparkizX** [comment]
Even though no theme is present at the moment problem persists

**Comment by JeanOUINA** [comment]
remove all plugins from devilbro too and reload lightcord

**Comment by SparkizX** [comment]
It is actually not that bad, what you have to do is open debug shit with `ctrl` + `shift` + `i` and pick the red shit and then in css uncheck `content`, once you do that, you are ready to go, and you will have to do this after restart of lightcord.

The question is diffrent, why is he doing that, what is his problem?
