### ISSUE TITLE
Some BD plugins dont work with Lightcord

### ISSUE THREAD

**Issue by vandyxd** [Lightcord/Lightcord#299]
**Describe the bug**
Devilbro plugins show ''Do not use lightcord" and some plugins dont load

**To Reproduce**
1. Add some plugins made by Devilbro 
2. Click on plugins
3. Scroll down to any devilbros plugins
4. ''dO NoT uSe LiGhTcOrD

**Desktop (please complete the following information):**
 - OS: windows 10
 - latest

**Comment by smartfrigde** [comment]
Just don't use his plugins

**Comment by smartfrigde** [comment]
It's not a bug on lightcord side. It's the author blocking usage for Lightcord users

**Comment by ryaniskira** [comment]
That's just Devildouche being Devildouche. He thinks Lightcord "stole" BetterDiscord so he's blocking Lightcord and spreading FUD about it.
