### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Sysys242** [Lightcord/Lightcord#300]
Hi,
I'm using lightcord for like 5 month and when i switched to windows, and lightcord take 20% of my CPU !!!!!!
http://sysybigbrain.tk/e8Uiz

I Don't know why, i have disable hardware optimisation,
Did you know how to fix it ?

**Comment by GermanBread** [comment]
Enable hardware-acceleration. Keeping it disabled tanks your CPU (and is a dumb idea).
