### ISSUE TITLE
when ever I click the user settings button whole screen goes grey[BUG]

### ISSUE THREAD

**Issue by braandoned** [Lightcord/Lightcord#302]
**Describe the bug**
when ever I click the user settings button whole screen goes grey

**To Reproduce**
1. Go to 'bottom left corner for discord'
2. Click on 'user settings'
3.

**Expected behavior**
I was supposed to see the discord user settings

**Screenshots**
![53PuQAvga](https://user-images.githubusercontent.com/83286776/125145976-b1396180-e0f1-11eb-8514-4d448a0fcbd5.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Version [Version	10.0.19042 Build 19042]

**Comment by smartfrigde** [comment]
Don't use DevilBro plugins
