### ISSUE TITLE
[BUG] 0PluginLibrary cannot run

### ISSUE THREAD

**Issue by AncuL001** [Lightcord/Lightcord#303]
**Describe the bug**

**To Reproduce**
1. just open lightcord

**Screenshots**
![](https://i.imgur.com/GfOwDdF.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Lightcord 0.1.8

**Additional context**
tbf i don't know if this is from Lightcord or ZeresPluginLibrary

**Comment by smartfrigde** [comment]
Disable plugin scanning or beg @JeanOUINA to update hashes
