### ISSUE TITLE
[BUG] No new tabs get opened

### ISSUE THREAD

**Issue by unexploredtest** [Lightcord/Lightcord#307]
**Describe the bug**
So, after I enable the "Lightcord Tabs" option, when I try to make a new tab via "Open a new Tab", nothing happens.

**To Reproduce**
1. Go to Lightscord Settings in User Settings
2. Enable "Lightcord Tabs" option
3. Click on "Open a new Tab"
4. Nothing happens

**Expected behavior**
A new tab opening

**Screenshots**
![notab](https://user-images.githubusercontent.com/53617231/125777793-b11464c0-592e-4da8-879e-3d6302a29112.png)

**Desktop (please complete the following information):**
 - OS: Tried on Windows and Linux (Manjaro)
 - Version 0.1.8, the latest one

**Comment by CE1CECL** [comment]
Try pressing

CTRL + T

It worked for me!

But!
there is a catch
the bot client in lightcord doesn't work properly (at least for me)

**Comment by unexploredtest** [comment]
Thanks, it worked!
Just a question, can I in a way keep the tabs after closing lightcord or restarting the system?

**Comment by smartfrigde** [comment]
No
