### ISSUE TITLE
[BUG] i have a theme on now settings are black

### ISSUE THREAD

**Issue by theharrasor** [Lightcord/Lightcord#312]
**Describe the bug**
i put a theme on to test it as it was new the theme was basicbackground i think a pretty popular one and now all my settings are pitch black and i cant see a thing but when i did it before in the past with the same theme there was no problem

**To Reproduce** i am not sure if it will or it was just a one time thing
1. Go to settings
2. Click on themes
3. put on basicbackground 

**Expected behavior**
the settings turn black and now everytime you try to go back into settings its just black

**Screenshots**
![image](https://user-images.githubusercontent.com/87761687/126485433-2b4d2f64-9db1-4fe9-a7a9-a3f1441ee9ec.png)
![image](https://user-images.githubusercontent.com/87761687/126485429-9c81d3a0-9352-4b2e-8387-19f4ba06af36.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7, Ubuntu, etc...]
 - windows 10
 - Version [e.g. v0.1.4]
 - lightcord version 1.8 the latest

**Additional context**
now i cant change the background or fix it i need help though it may be because i do also have the like 3 lines for discord servers theme on aswell

**Comment by smartfrigde** [comment]
That's not Lightcord bug. DevilBro blacklisted his plugins and themes from working on Lightcord.

**Comment by theharrasor** [comment]
> That's not Lightcord bug. DevilBro blacklisted his plugins and themes from working on Lightcord.

so how do i fix it?

**Comment by smartfrigde** [comment]
Get rid of devilbro plugins and themes

**Comment by GBKAlfrado** [comment]
> Get rid of devilbro plugins and themes

how'd you do this?
