### ISSUE TITLE
[BUG] First time launch and then crashes

### ISSUE THREAD

**Issue by Arion-Kun** [Lightcord/Lightcord#32]
**Describe the bug**
First time launching Lightcord, never used before, Enabled Developer options, tried to access Components Preview and Account Info only to be met with crashes.

**To Reproduce**
1. Go to settings
2. Click on Account Info 
3. See Crash

**Expected behavior**
Not Crash

**Screenshots**
![image](https://user-images.githubusercontent.com/53127594/91655917-ad41b980-eab4-11ea-92f6-58a2674d8310.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Build 2004

**Additional context**
--

**Comment by Arion-Kun** [comment]
Additional Info: 
![image](https://user-images.githubusercontent.com/53127594/91655973-1e816c80-eab5-11ea-8044-a2b9c23f60cd.png)

**Comment by JeanOUINA** [comment]
Thank you for your issue.

This was already fixed in the dev build. Please use these instead. 
Windows: https://lightcord.deroku.xyz/api/gh/releases/Lightcord/Lightcord/dev/lightcord-win32-ia32.zip
Linux: https://lightcord.deroku.xyz/api/gh/releases/Lightcord/Lightcord/dev/lightcord-linux-x64.zip
