### ISSUE TITLE
[BUG] Unable to send any emote to other Lightcord users

### ISSUE THREAD

**Issue by SethFalco** [Lightcord/Lightcord#325]
**Describe the bug**
I'm unable to send emojis to other Lightcord users in the way I'd expect based on the feature list.

> Free Emotes - Send any emote to other Lightcord users!
> \- https://github.com/Lightcord/Lightcord/blob/master/README.md#features

![image](https://user-images.githubusercontent.com/22801583/129017063-e7a58a2c-61bd-49e4-bed3-7ac06aa6b801.png)

I've been testing this by trying an emote called `pandaAww` from a guild I'm in:
* .pandaAww
* .:pandaAww:
* .pandaAww.
* :.pandaAww:
* pandaAww
* :pandaAww:

**To Reproduce**
1. Go to a text channel.
2. Attempt to do an emote that would otherwise require Nitro.
3. Nothing happens, and when sending the message it just sends literally.

**Expected behavior**
I'm not 100% sure about what the intended behavior is as I'm brand new to Lightcord, but looking at the code it looks like an emoji picker is meant to appear if I use the emoji prefix?

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version v0.1.9

**Additional context**
I've been looking at this and have no idea what I'm doing.
I can see the issue is ultimately because `AutoCompletionTemplates` is undefined, but not sure what it should be.

Related to: https://github.com/Lightcord/Lightcord/pull/324

**Comment by JeanOUINA** [comment]
broken and unlikely to be fixed
