### ISSUE TITLE
Sidebar not loading when logged into bot account

### ISSUE THREAD

**Issue by WoffleTbh** [Lightcord/Lightcord#326]
Sidebar will keep "loading" when you're logged into a bot account
![Screenshot from 2021-08-13 21-44-38](https://user-images.githubusercontent.com/79484501/129410866-50f4e44c-4bda-4734-a37d-6b8440e2dd67.png)
(I'm on Ubuntu Linux)

**Comment by technicaldiff** [comment]
have you enable server member intents for the bot?
