### ISSUE TITLE
0BDFDB Plugin blocks settings

### ISSUE THREAD

**Issue by Behelden** [Lightcord/Lightcord#327]
0BDFDB from https://betterdiscord.app/plugin/BDFDB, causes issue where all settings have disappeared. Have used Sandboxie to try isolate the issue, cannot find the cause.
GPU: 5700XT latest driver as of 14th August.

![image](https://user-images.githubusercontent.com/55672265/129458734-1e4245f6-0ac9-401d-819a-ee2c6658abea.png)

Removing BDFDB fixes issue on Lightcord running on both USB, Sandboxie and default installation.

**Comment by smartfrigde** [comment]
Not lightcord bug. It's just memorybro protecting lightcord from memory leaks
