### ISSUE TITLE
[BUG] The scoop installer installs the 32 bit version on a 64 bit machine

### ISSUE THREAD

**Issue by aminya** [Lightcord/Lightcord#331]
**Describe the bug**
The scoop installer installs the 32 bit version on a 64 bit machine
```
Installing 'lightcord' (0.1.9) [64bit]
lightcord-win32-ia32.zip (136.8 MB) [========================>                                                ]  34%
Terminate batch job (Y/N)? Y
```

**To Reproduce**
```
 scoop install lightcord
```

**Expected behavior**
Install the 64 bit version

**Screenshots**
![image](https://user-images.githubusercontent.com/16418197/131198752-0f68216e-e9c5-4107-b0cb-b7e23d340371.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7, Ubuntu, etc...] Win 11 build 168
 - Version [e.g. v0.1.4] 0.1.9

**Additional context**

**Comment by JeanOUINA** [comment]
There is no 64 bits version. Only 32 because of limitations with native module. We can’t make this work with 64 bits. Sorry.
