### ISSUE TITLE
Installation error: ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by CuriousApe2020** [Lightcord/Lightcord#336]
Both when trying to install Lightcord from Terminal and Manjaro Appstore I get the same error:

```
==> Validating source files with md5sums...
    lightcord-git ... Skipped
    Lightcord.desktop ... FAILED
    lightcord.png ... Passed
==> ERROR: One or more files did not pass the validity check!
```

Full readout:

git clone https://aur.archlinux.org/nvm && git clone https://aur.archlinux.org/lightcord-git.git && \
    cd nvm && makepkg -si && \
        cd ../lightcord-git && makepkg -si
Cloning into 'nvm'...
remote: Enumerating objects: 213, done.
remote: Counting objects: 100% (213/213), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 213 (delta 82), reused 212 (delta 82), pack-reused 0
Receiving objects: 100% (213/213), 40.05 KiB | 931.00 KiB/s, done.
Resolving deltas: 100% (82/82), done.
Cloning into 'lightcord-git'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 121 (delta 18), reused 120 (delta 17), pack-reused 0
Receiving objects: 100% (121/121), 36.85 KiB | 857.00 KiB/s, done.
Resolving deltas: 100% (18/18), done.
==> Making package: nvm 0.38.0-2 (Di 07 Sep 2021 19:11:28 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading nvm-0.38.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119  100   119    0     0    393      0 --:--:-- --:--:-- --:--:--   392
100  151k    0  151k    0     0   190k      0 --:--:-- --:--:-- --:--:--  190k
  -> Found init-nvm.sh
  -> Found install-nvm-exec
==> Validating source files with sha256sums...
    nvm-0.38.0.tar.gz ... Passed
    init-nvm.sh ... Passed
    install-nvm-exec ... Passed
==> Extracting sources...
  -> Extracting nvm-0.38.0.tar.gz with bsdtar
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "nvm"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: nvm 0.38.0-2 (Di 07 Sep 2021 19:11:31 CEST)
==> Installing package nvm with pacman -U...
[sudo] password for chris: 
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) nvm-0.38.0-2

Total Installed Size:  0,13 MiB
Net Upgrade Size:      0,00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) upgrading nvm                                [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Making package: lightcord-git 0.1.7.r11.g3c4c7de-2 (Di 07 Sep 2021 19:11:37 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning lightcord-git git repo...
Cloning into bare repository '/home/chris/lightcord-git/lightcord-git'...
remote: Enumerating objects: 5773, done.
remote: Counting objects: 100% (589/589), done.
remote: Compressing objects: 100% (282/282), done.
remote: Total 5773 (delta 327), reused 498 (delta 297), pack-reused 5184
Receiving objects: 100% (5773/5773), 306.98 MiB | 5.63 MiB/s, done.
Resolving deltas: 100% (3776/3776), done.
  -> Found Lightcord.desktop
  -> Downloading lightcord.png...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19479  100 19479    0     0  65912      0 --:--:-- --:--:-- --:--:-- 65807
==> Validating source files with md5sums...
    lightcord-git ... Skipped
    Lightcord.desktop ... FAILED
    lightcord.png ... Passed
==> ERROR: One or more files did not pass the validity check!

**Comment by pryme-svg** [comment]
Should be fixed now

**Comment by CuriousApe2020** [comment]
Yes, it works now. Thank you.
