### ISSUE TITLE
Hey again

### ISSUE THREAD

**Issue by FieryMewtwo** [Lightcord/Lightcord#337]
So you might remember me from when I asked about why the portable version saves themes to AppData. I get that it's intended to do this, but what would I have to do to change that to a different path?

**Comment by dodobirbb** [comment]
welp

**Comment by dodobirbb** [comment]
lightcord creators no longer support lightcord anymore

**Comment by dodobirbb** [comment]
dont ask for support in their server because anyone is asking for support for lightcord gets banned after few seconds so just switch to client mods like bd, pc, gm, etc

**Comment by dodobirbb** [comment]
btw sorry for talking via my another github account

**Comment by DodoGames7** [comment]
heres a proof that im saying the truth: 
![image](https://user-images.githubusercontent.com/69091682/132588586-0eb66d1b-10bd-4595-9102-a04bdc337f9f.png)

**Comment by DodoGames7** [comment]
and also this too: 
![image](https://user-images.githubusercontent.com/69091682/132589303-f743e335-247d-4a70-bc70-21eda8456cd1.png)

**Comment by FieryMewtwo** [comment]
Oh, ok then. I'll just use BandagedBD. Thanls for the info!

**Comment by DodoGames7** [comment]
np
