### ISSUE TITLE
[FEATURE] I Cant Hide My Bots Presence.

### ISSUE THREAD

**Issue by XplodinNdr08** [Lightcord/Lightcord#342]
I Cant Find A Way To Hide My Bots Presence And I Dont Want Fortnite/Minecraft Players Get Mad At Me For Playing Minecraft/Fortnite And I Cant Hide Its Presence So Thats Why I Want To Hide Its Presence But Yet I Cant.
Normal Discord Has This Option But LightCord Doesnt Could You Please Add The Feature To Hide The Bots Presence?

**Comment by JeanOUINA** [comment]
don't use lightcord
