### ISSUE TITLE
[BUG] ZeresPluginLibrary detects as a malware

### ISSUE THREAD

**Issue by shifting-tides** [Lightcord/Lightcord#343]
![image](https://user-images.githubusercontent.com/63145386/132993368-a1ff1566-d30d-4202-a4fb-4c19c3216772.png)
https://github.com/rauenzi/BDPluginLibrary/blob/a2de24db5063a0e317f273c3d08b771c6b8d4495/release/0PluginLibrary.plugin.js

ZeresPluginLibrary was detected as a malware by plugin certifier and it ruined the workflow of legitimate plugins. Updating the hashes would help i guess?

**Comment by DodoGames7** [comment]
just turn it off theres no point of keeping it on lmao

**Comment by shifting-tides** [comment]
i want plugin certifier to be fixed tho

**Comment by JeanOUINA** [comment]
don't use lightcord
