### ISSUE TITLE
Archive the repo 

### ISSUE THREAD

**Issue by DodoGames7** [Lightcord/Lightcord#349]
Archive it so there will be no new issues , pull requests since lightcord is discontinued lmao why not?

**Comment by DodoGames7** [comment]
Archive it DO IT

**Comment by DodoGames7** [comment]
0  sense

**Comment by DodoGames7** [comment]
mans lazy to archive a shitcord

**Comment by JeanOUINA** [comment]
e

**Comment by DodoGames7** [comment]
lmao imagine closing this issue

**Comment by DodoGames7** [comment]
Ez

**Comment by DodoGames7** [comment]
Magic
