### ISSUE TITLE
[BUG] LightcordBD Not Loading on Windows 10

### ISSUE THREAD

**Issue by rckyx** [Lightcord/Lightcord#351]
My Lightcord takes a long time to load, but when it does I get booted up with the original Discord with the Lightcord logo in the bottom right corner flashing in and out and when I hover my cursor over it, it says "LightcordBD is loading.." or something along those lines. Usually when I boot it up, it'll load immediately, but now it does this. No matter how long I wait, it doesn't load LightcordBD.

1. Download Lightcord on Windows 10.
2. Use it a couple of times alternatively with the real Discord client as well.
3. One day, it should do this.
4. Not be able to load into Lightcord for several hours.

I expect it to always load up straight away like it used to, but it's like the new update caused this, because it only loaded once after this new update.

![ss1](https://user-images.githubusercontent.com/91694543/135512746-e3c8e93f-7bb1-466f-87e7-c7e9c7fc4e21.png)
![Uploading ss2.png…]()

I am on the latest version of Windows 10

It worked before but for some random reason this occured and it never loaded up normally since.

**Comment by JeanOUINA** [comment]
shut up

**Comment by rckyx** [comment]
> shut up

your granny stinks

**Comment by JeanOUINA** [comment]
your mom stinks more---- On jeu., 30 sept. 2021 21:12:38 +0200  ***@***.******@***.***> wrote ---- 
 
shut up 
 
your granny stinks

**Comment by rckyx** [comment]
> your mom stinks more---- On jeu., 30 sept. 2021 21:12:38 +0200 ***@***.******@***.***> wrote ---- shut up your granny stinks —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

you smell like a cactus with ptsd shut up

**Comment by JeanOUINA** [comment]
you smell like a retard trying to use lightcord

**Comment by rckyx** [comment]
> you smell like a retard trying to use lightcord

i alr fixed it + u smell like a thanksgiving turkey covered in monkey semen and cat litter

**Comment by DodoGames7** [comment]
Lmao shut the fuck lts discontinued lmao @rckyx
