### ISSUE TITLE
[BUG] Lightcord darwin wont work make it a dmg file cuz zip files ruin the app.

### ISSUE THREAD

**Issue by ItsMeNotFound** [Lightcord/Lightcord#352]
**Describe the bug**
on macos the actual app will not be complied properly because of zip try and use dmg

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7, Ubuntu, etc...]
 - Version [e.g. v0.1.4]

**Additional context**

**Comment by JeanOUINA** [comment]
shut up
