### ISSUE TITLE
[BUG] High GPU usage 

### ISSUE THREAD

**Issue by stnert** [Lightcord/Lightcord#354]
When running the application, GPU usage increases exponentially and is between 98-99% usage. 

![unknown](https://user-images.githubusercontent.com/48295298/135721717-8d120b2d-2a06-4922-a904-d1436f2cca0a.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [e.g. v0.1.9]

**Comment by JeanOUINA** [comment]
shut up idc

**Comment by stnert** [comment]
WAT?

**Comment by stnert** [comment]
@JeanOUINA Man, stop being a son of a bitch and think about this bug

**Comment by stnert** [comment]
@JeanOUINA Dude go fuck yourself, and help spread the word or fix the bug!

**Comment by bettydreemurr** [comment]
@stnert  hum, i think lightcord is discontinued lmfao

![](https://user-images.githubusercontent.com/87833862/135714381-8a2055b0-c090-402f-958f-5bf0e85a6ab6.png)

**Comment by JeanOUINA** [comment]
yeah that’s why I said shut up, it’s discontinued, and each time someone sends an issue/a message in an issue, I get an email

**Comment by bettydreemurr** [comment]
lmfaoo

**Comment by DodoGames7** [comment]
bruh

**Comment by GermanBread** [comment]
I have no idea how you got past the warning in the installer but ok
(you probably used the AppImage or the tarball)

**Comment by micwoj92** [comment]
@JeanOUINA 
![image](https://user-images.githubusercontent.com/45581170/135766428-309a3655-2f53-499b-8652-e16725f64c48.png)

**Comment by JeanOUINA** [comment]
ok

**Comment by DodoGames7** [comment]
Shut the fuck up lts discontinued lmao

**Comment by DodoGames7** [comment]
Shit wrong reply
