### ISSUE TITLE
[BUG] Clicking "public" under discord logo (top left) makes the window irreversibly blank 

### ISSUE THREAD

**Issue by MayorUshanka** [Lightcord/Lightcord#38]
I just downloaded lightcord from the AUR repos. I logged in, and wanted to mess around and see what it's about.

I saw a thing "PUBLIC" under the purple discord logo in the servers/friends tray, so I clicked on it. Now the window title says "@Bonko Donko - Lightcord".

https://imgur.com/Ioz2jEO.png

Restarting the client fully fixed it.

Starting the client from the terminal, no output occurs when I click on PUBLIC.

**Comment by unixkeys** [comment]
we know

**Comment by unixkeys** [comment]
to be more serious, this is a BBD issue and this can just be disabled from the BetterDiscord settings

**Comment by JeanOUINA** [comment]
Still fixed in master tho. I’m closing this because we aew aware and already fixed it.
