### ISSUE TITLE
[BUG] Thicc Icon

### ISSUE THREAD

**Issue by UltraBlackLinux** [Lightcord/Lightcord#39]
**Screenshots**
![Screenshot_20200911_210809](https://user-images.githubusercontent.com/62404294/92963609-06c1c500-f473-11ea-968b-8bc6a683ee28.png)
^ Hmmmm -  Discord Canary + Lightcord ^
Please add an option to change the icon - I dont like the LC icon that much :|
**Desktop (please complete the following information):**
 - OS: Manjaro KDE
 - Version 0.1.4

**Comment by Oof4** [comment]
bruh what issue is this

**Comment by PoorPocketsMcNewHold** [comment]
Firstly, It would be probably better, to compare it with the default Discord Canary (in your case), program icon. Trying to stick ourselves, to comply with a third-party community icon pack, is just not something to do.

**Comment by pryme-svg** [comment]
You can create your own icon and copy it to /usr/share/pixmaps to overwrite the current svg file if you wish
