### ISSUE TITLE
[BUG] stupid click to update shows, when iredownload

### ISSUE THREAD

**Issue by Oof4** [Lightcord/Lightcord#45]
its so annoying, why is it there?! can you fix this please

**Comment by JeanOUINA** [comment]
first, can you provide a screenshot to be sure we’re talking about the same thing ?
next, this isn’t a lightcord problem, this is due to one of your plugin (ZeresPluginLibrary), try updating it manually

**Comment by Oof4** [comment]
oh ok lemme see thanks
