### ISSUE TITLE
[BUG?] Can't login with a Discord Bot Token

### ISSUE THREAD

**Issue by WyteKnight** [Lightcord/Lightcord#47]
**Describe the bug**
Hello,
I downloaded Lightcord to have access to my bot and login with the bot token, to write with is without using a command like /say or whatever. However, when I am on the login page, I can write in the token text field, but whatever I type nothing appear. It stay empty. Even if I paste something inside with either ctrl+v or right click paste. If it can help, I am running a Windows 7 64 bits.

**Comment by JeanOUINA** [comment]
this is a display bug, but your input is correctly typed in.

(also bot login is broken atm because of a Discord Api Change)

**Comment by WyteKnight** [comment]
Ok thanks. Do you know when the bot login will work again? It works on Snazzah's lightcord bot login tho, https://snazzah.github.io/Lightcord/

**Comment by JeanOUINA** [comment]
> It works on Snazzah's lightcord bot login tho, snazzah.github.io/Lightcord
He uses Discord.JS, which is updated to work with the latest Discord Api for **bots**, and it requires us to add a field (`intents`) only in bot login, which is pretty hard because we don't know if it's a bot before actually connecting to discord.

**Comment by WyteKnight** [comment]
Okay, noted.
Do you know if you will be able to fix it or not? Or maybe make an alternate version to login as a bot?

**Comment by JeanOUINA** [comment]
We have two choices:
 1. Add a checkbox to indicate it's a bot
 2. Attempt a connection without the intent, if it fails, retry with intent

**Comment by WyteKnight** [comment]
Okay. Maybe can you detect when something is entered in the token field and if it's not empty connect with intent too ? It will be much simpler for the user this way. The checkbox works fine imho, if you're messing around with bots and installing a alternate discord client you should be able to see a checkbox and tick it.

Do you have any ETA about when you will make a decision and dev it or absolutely not?

**Comment by JeanOUINA** [comment]
Fixed, and updated dev builds.

[Windows](https://lightcord.deroku.xyz/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-win32-ia32.zip)
[Windows Portable](https://lightcord.deroku.xyz/api/gh/releases/Lightcord/Lightcord/dev/lightcord-win32.exe)
[Linux](https://lightcord.deroku.xyz/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-linux-x64.zip)
[Mac](https://lightcord.deroku.xyz/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-darwin.zip)

Use them if you want to use bot login.

**Comment by WyteKnight** [comment]
Thanks a lot. (:
