### ISSUE TITLE
Techicaly, its a virus [BUG]

### ISSUE THREAD

**Issue by GamingWorld-Discord** [Lightcord/Lightcord#50]
**Describe the bug**
360 Total Security and other BEST(S) Antiviruses, check it as a trojan34/. So I can't download it.

**To Reproduce**
1. Go to 'download'
2. Click on 'download'
3. check it to viruses

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [That don't need, it's working with all versions]

**Comment by unixkeys** [comment]
Technically*
false positive, probably because of nexe and downloading files from internet
