### ISSUE TITLE
[BUG] Krisp noise reduction missing

### ISSUE THREAD

**Issue by awesomehaze** [Lightcord/Lightcord#52]
**Describe the bug**
Krisp noise reduction option not shown.

**To Reproduce**
1. Join any voice call
2. Notice that there is no krisp noise reduction icon to the left of the disconnect button

**Expected behavior**
The krisp icon should show to the left of the disconnect button

**Screenshots**
![image](https://user-images.githubusercontent.com/48741653/95139876-5cac2480-0722-11eb-8318-a506d0caeab2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v0.1.4 (80b2b93)

**Comment by Arion-Kun** [comment]
I asked them about this in their support channel's discord a while back, their reason why its not there was iirc that its hard to implement as KRISP does some things to prevent it from being in non-native-discord

**Comment by JeanOUINA** [comment]
yeah, sorry I couldn’t respond earlier. Discord checks the executable signing, to prevent use from a non-Discord application. That means we can’t use it.

**Comment by DrewDaPilot** [comment]
Why not just upgrade the discord version used by Light cord? Its a pretty important feature to be left out.

**Comment by smartfrigde** [comment]
There's just no way. At least for now. Also this is closed if you didn't notice.

**Comment by DrewDaPilot** [comment]
I did notice, but I have some reverse engineering skills and may be able to find a bypass of the signature check outlined above.

**Comment by smartfrigde** [comment]
h hacler 1337, guys he's gonna hack us all!!1
Also I think you should wait for rewrite if ya doing this🐩
