### ISSUE TITLE
Discord BD Problem[BUG]

### ISSUE THREAD

**Issue by ZPenux** [Lightcord/Lightcord#55]
for some reason i can't disable any thing in discord plugins settings ( tested on 4 plugins )
note : tested discord bd on normal discord client and works fine

![bd](https://user-images.githubusercontent.com/70713896/96128310-78b77f00-0ef5-11eb-85e9-9ed33020f02d.gif)

**Comment by ZPenux** [comment]
oh wait i will attach the full gif because its no't full gif

**Comment by pryme-svg** [comment]
same happens to me

**Comment by msPornHub** [comment]
this maybe is a plugin issue
@JeanOUINA

**Comment by JeanOUINA** [comment]
It’s a plugin issue. Check at rauenzi/BDPluginLibrary
