### ISSUE TITLE
[BUG] AUR package broken

### ISSUE THREAD

**Issue by pryme-svg** [Lightcord/Lightcord#56]
After installing the AUR package, the tabs for the lightcord features show an error occurred. 

**To Reproduce**
1. Go to Settings
2. Click on Lightcord Settings
3. See error

**Expected behavior**
The tab should allow you to change settings for lightcord

 - Arch Linux x86_64

**Additional context**
I know that we cannot fix the package, and I have contacted the maintainer of the package. However, I think there should be an indication at least on the readme guiding users to the upstream package.

**Comment by JeanOUINA** [comment]
duplicate of #54 ?

**Comment by pryme-svg** [comment]
Just saw that issue.

**Comment by JeanOUINA** [comment]
Also we’re providing scripts to install the dev build in our discord: https://lightcord.org/discord

**Comment by pryme-svg** [comment]
Consider appending something about it to the readme?
