### ISSUE TITLE
[FEATURE] Subreddit

### ISSUE THREAD

**Issue by pryme-svg** [Lightcord/Lightcord#65]
Maybe create a subreddit for lightcord cuz y not.

**Comment by msPornHub** [comment]
"To prevent spam, accounts must be at least 30 days old and have enough positive karma to create communities."
fuck reddit

**Comment by pryme-svg** [comment]
I am requesting it on redditrequest

**Comment by msPornHub** [comment]
ok daddy

**Comment by pryme-svg** [comment]
you are so annoying

**Comment by pryme-svg** [comment]
bruh my account has to be 90 days old fuck reddit I already have 3k karma

**Comment by Oof4** [comment]
bruh

**Comment by JeanOUINA** [comment]
uh

**Comment by PoorPocketsMcNewHold** [comment]
@pryme-svg 

1.  Why post things on reddit about lightcord ?
2.  Do you think people have an interest to create a subreddit ?
3.  What would an individual, prefer reddit over the Lightcord server ?
4.  Why using reddit is necessary for you ? (See @msPornHub comment on one particular reddit rule) More open alternatives exist.

**Comment by Oof4** [comment]
> @pryme-svg 
> 
> 1. Why post things on reddit about lightcord ?
> 2. Do you think people have an interest to create a subreddit ?
> 3. What would an individual, prefer reddit over the Lightcord server ?
> 4. Why using reddit is necessary for you ? (See @msPornHub comment on one particular reddit rule) More open alternatives exist.

ye yeah true

**Comment by unixkeys** [comment]
> says "ye yeah true" instead of actually answering to the questions :neckbeard: 
we should get back r/Lightcord though for safety, i guess
