### ISSUE TITLE
[FEATURE] aea

### ISSUE THREAD

**Issue by msPornHub** [Lightcord/Lightcord#73]
update the download links of <#706082364199010337> with dev build

**Comment by pryme-svg** [comment]
what file

**Comment by msPornHub** [comment]
[thiz](https://weebs.xyz/5Ww2eE2W)

**Comment by pryme-svg** [comment]
wtf do u want

**Comment by pryme-svg** [comment]
windooze or linux i self compiled the dev

**Comment by msPornHub** [comment]
sex

**Comment by pryme-svg** [comment]
go away annoying anon

**Comment by msPornHub** [comment]
no u
