### ISSUE TITLE
[BUG]Lightcord is considered a virus by Bitdefender and is removed automatically

### ISSUE THREAD

**Issue by AZ3TheDragon** [Lightcord/Lightcord#81]
**Describe the bug**
When installing Lightcord, Bitdefender blocks it and reports it as an "Atc4.Detection"

**To Reproduce**
1. Install Lightcord with Bitdefender on
2. *disinfection in progress*
3. Lightcord is broken

**Expected behavior**
Install Lightcord and it won't show as a threat to Bitdefender

**Screenshots**
(https://user-images.githubusercontent.com/29930926/96947507-60290500-14b1-11eb-9bd9-400bce423dd3.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1909

**Additional context**

**Comment by 7lq** [comment]
this is normal.

**Comment by JeanOUINA** [comment]
try to whitelist Lightcord in your antivirus

**Comment by ControlAlternateDelete** [comment]
I think this is normal. Microsoft SmartScreen said Lightcord might be unsafe.

**Comment by kekkodance** [comment]
It's not unsafe. The code is fully open source, the smartscreen warning gets trripped because of no signature. A signature costs a ton of money for 1 year.

**Comment by ControlAlternateDelete** [comment]
> It's not unsafe. The code is fully open source, the smartscreen warning gets trripped because of no signature. A signature costs a ton of money for 1 year.

I said _this is normal_. I just ignored SmartScreen (note: unless you trust the guy who coded the program, never ignore smartscreen)
