### ISSUE TITLE
[BUG] Graphical Bug in settings

### ISSUE THREAD

**Issue by Ixkt** [Lightcord/Lightcord#82]
The bug is a graphical bug in the settings of LightCord
- OS: Windows 10

When i go in the settings i see this bug :
![Screenshot_2](https://user-images.githubusercontent.com/23583495/97110430-9052ec80-16d9-11eb-9a2d-55e1d2ffe4c1.png)

**Comment by JeanOUINA** [comment]
duplicate of #54
