### ISSUE TITLE
[SECURITY]

### ISSUE THREAD

**Issue by 1nfdev** [Lightcord/Lightcord#88]
What do you think about that?

**LightcordSetup.exe**: https://www.virustotal.com/gui/file/09552db0bac6f351d4afea167790b9ce5cb2e3824c4e7ae2015839cb32ab4307/detection

**Comment by BlackOfWorld** [comment]
Installer is open source, it's a false positive.

**Comment by GermanBread** [comment]
These are only three AV engines. As long as the major AV engines don't detect it, it is safe.

**Comment by JReverse** [comment]
@BlackOfWorld @GermanBread @1nfdev it Seem'd to start encoding on run hmmmm once I closed still did until a killed a Nvidia Container could be a bug but i can't even use it Dosen't seem to work properly so many crashes

**Comment by ItzSeifsUniverse** [comment]
Try The Dev Version Then. Also, That's The Only One It Detects.

Its Probably A False Positive

**Comment by Oof4** [comment]
Try The Dev Version Then. Also, That's The Only One It Detects.

Its Probably A False Positive

**Comment by 1nfdev** [comment]
*lightcord-win32.exe*: https://www.virustotal.com/gui/file/fc498d3ce1b63a0e189535d943d5e4aaee5861dd6808576909a0fefc2a8d48cf/detection
*LightcordSetup-dev.exe*: https://www.virustotal.com/gui/file/2e9f8945c21850b114280d1f330309a285004b2c64f7835d19d4813a030a4634/detection

The dev-version of the installer likewise receives a trojan label, but a standalone executable doesn't have this.

So, I think this is a false positive or a problem in the installation builder. In my opinion this is a problem must be solved.

**Comment by erkinalp** [comment]
Where is @night ?
