### ISSUE TITLE
Completely unresponsive in v0.1.4

### ISSUE THREAD

**Issue by danielsouzat** [Lightcord/Lightcord#9]
**System:** Arch Linux with Gnome
**Description:** Interface is completely unresponsive after update.
**Version:** 0.14

As you can see in the screenshot bellow the app loads but don't respond to my actions. I'm unable to close the release notes popup. If I restart it closes automatically but that doesn't change anything as the app will load the expected screen but will not respond to my actions. I tried cleaning all my config and cache files but that changed nothing. Reverting to 0.1.3 solves the problem.

![Screenshot from 2020-07-31 19-15-53](https://user-images.githubusercontent.com/13279154/89081786-7fa50b80-d362-11ea-8b0f-24b2b25e0bcd.png)

**Console stdout:** 

```
Initializing Lightcord.
Version: 0.0.306
releaseChannel: stable
commit: 2dd4315b3971a6a3af7133b67f5cb86f41a7386b
Starting with version 0.1.4 because it haven't been 1 week since the last check.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

**Developer console log:**

[lightcord.log](https://github.com/Lightcord/Lightcord/files/5009269/lightcord.log)

*I tried to anonimize what could be personal or session data in the log.*

**Comment by JeanOUINA** [comment]
Thank you for your issue.

By looking at the logs, I think I found the error, but I can't test as this bug only appear on Linux and I'm on windows.

Can you test [this build](https://lightcord.deroku.xyz/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-linux-x64.zip) (or replace the app.asar with [this one](https://lightcord.deroku.xyz/api/v1/gh/releases/Lightcord/Lightcord/dev/app_linux.asar)) and tell me if lightcord is working now ?

**Comment by danielsouzat** [comment]
It worked!
