### ISSUE TITLE
A blank, grey screen upon opening

### ISSUE THREAD

**Issue by ControlAlternateDelete** [Lightcord/Lightcord#90]
Upon opening Lightcord and pressing a button labled "public" there is a grey screen that has labels when you hover over random places with your cursor.

1. Open Lightcord after installation
2. Press "public" button. It can be found at the top left
2. See error

**Expected behavior**
As this isn't in the vanilla Discord client, I don't know what should happen.

**Screenshots**
Screenshot attached below

**Desktop:**
 - OS: Windows 10 Home
 - Version 20H2

![image](https://user-images.githubusercontent.com/73121484/97416335-354e0f00-18fe-11eb-8a46-264205817c87.png)

**Comment by JeanOUINA** [comment]
maybe can you provide any screenshot ?

**Comment by ControlAlternateDelete** [comment]
There is also an error with the Lightcord settings that says that the settings could not be loaded.

**Comment by ControlAlternateDelete** [comment]
This bug will be closed. I have fixed this bug by downloading another version of Lightcord
