### ISSUE TITLE
[FEATURE] MacOS build

### ISSUE THREAD

**Issue by DarkFlame57** [Lightcord/Lightcord#91]
Feature request: making macOS build.

**Comment by JeanOUINA** [comment]
This build should work: https://lightcord.org/api/v1/gh/releases/Lightcord/Lightcord/dev/lightcord-darwin-x64.zip
We’ll drop official macOS support on the next version.

**Comment by DarkFlame57** [comment]
Maybe somewhere I can get build instructions? Running with npm isn't the nicest way.

**Comment by JeanOUINA** [comment]
I mean:
`devInstall`: `node scripts/devInstall`
`build`: 
1. `node scripts/build.js`
 2. `electron-builder build --mac`

if you really don't want to use npm

**Comment by DarkFlame57** [comment]
Well, this build goes frozen on the following screen:
![Снимок экрана 2020-10-28 в 01 31 47](https://user-images.githubusercontent.com/49563183/97369258-9e616280-18bd-11eb-8f0d-abebf6aed83e.png)

And I don't mind to use NPM, in fact I just want to build Lightcord so I don't have to `npm run run` it.
