### ISSUE TITLE
[BUG] Crash When you click on creators discord name in #showcase in discord

### ISSUE THREAD

**Issue by JReverse** [Lightcord/Lightcord#92]
**Describe the bug**

When you click on creators discord name in #showcase it crashes discord

**To Reproduce**
1. Go to #showcase
2. Click on Not Thomiz
4. See Crash

**Expected behavior**
Crash

**Screenshots**
https://prnt.sc/v8cpcm

**Desktop (please complete the following information):**
 - Windows 10
 - 2004

**Additional context**

**Comment by GermanBread** [comment]
Do you have any plugins enabled? If so, disable all and try to identify the plugin causing the issue.

**Comment by JReverse** [comment]
Solved was a color plugin conflicting.
