### ISSUE TITLE
[BUG] when i go BetterDiscord setting it's says error and account info crash my discord

### ISSUE THREAD

**Issue by spocewastoken** [Lightcord/Lightcord#95]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7, Ubuntu, etc...]
 - Version [e.g. v0.1.4]

**Additional context**

**Comment by JeanOUINA** [comment]
#54 redownload in the release tab
